// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdigitrec.h"

extern XDigitrec_Config XDigitrec_ConfigTable[];

XDigitrec_Config *XDigitrec_LookupConfig(u16 DeviceId) {
	XDigitrec_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDIGITREC_NUM_INSTANCES; Index++) {
		if (XDigitrec_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDigitrec_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDigitrec_Initialize(XDigitrec *InstancePtr, u16 DeviceId) {
	XDigitrec_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDigitrec_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDigitrec_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

