// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDIGITREC_H
#define XDIGITREC_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdigitrec_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XDigitrec_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XDigitrec;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDigitrec_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDigitrec_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDigitrec_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDigitrec_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDigitrec_Initialize(XDigitrec *InstancePtr, u16 DeviceId);
XDigitrec_Config* XDigitrec_LookupConfig(u16 DeviceId);
int XDigitrec_CfgInitialize(XDigitrec *InstancePtr, XDigitrec_Config *ConfigPtr);
#else
int XDigitrec_Initialize(XDigitrec *InstancePtr, const char* InstanceName);
int XDigitrec_Release(XDigitrec *InstancePtr);
#endif

void XDigitrec_Start(XDigitrec *InstancePtr);
u32 XDigitrec_IsDone(XDigitrec *InstancePtr);
u32 XDigitrec_IsIdle(XDigitrec *InstancePtr);
u32 XDigitrec_IsReady(XDigitrec *InstancePtr);
void XDigitrec_EnableAutoRestart(XDigitrec *InstancePtr);
void XDigitrec_DisableAutoRestart(XDigitrec *InstancePtr);

void XDigitrec_Set_training_data_V(XDigitrec *InstancePtr, u64 Data);
u64 XDigitrec_Get_training_data_V(XDigitrec *InstancePtr);
void XDigitrec_Set_testing_data_V(XDigitrec *InstancePtr, u64 Data);
u64 XDigitrec_Get_testing_data_V(XDigitrec *InstancePtr);
void XDigitrec_Set_results_V(XDigitrec *InstancePtr, u64 Data);
u64 XDigitrec_Get_results_V(XDigitrec *InstancePtr);

void XDigitrec_InterruptGlobalEnable(XDigitrec *InstancePtr);
void XDigitrec_InterruptGlobalDisable(XDigitrec *InstancePtr);
void XDigitrec_InterruptEnable(XDigitrec *InstancePtr, u32 Mask);
void XDigitrec_InterruptDisable(XDigitrec *InstancePtr, u32 Mask);
void XDigitrec_InterruptClear(XDigitrec *InstancePtr, u32 Mask);
u32 XDigitrec_InterruptGetEnabled(XDigitrec *InstancePtr);
u32 XDigitrec_InterruptGetStatus(XDigitrec *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
