// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of theta
//        bit 31~0 - theta[31:0] (Read/Write)
// 0x14 : Data signal of theta
//        bit 31~0 - theta[63:32] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of s
//        bit 31~0 - s[31:0] (Read/Write)
// 0x20 : Data signal of s
//        bit 31~0 - s[63:32] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of c
//        bit 31~0 - c[31:0] (Read/Write)
// 0x2c : Data signal of c
//        bit 31~0 - c[63:32] (Read/Write)
// 0x30 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCORDIC_CONTROL_ADDR_AP_CTRL    0x00
#define XCORDIC_CONTROL_ADDR_GIE        0x04
#define XCORDIC_CONTROL_ADDR_IER        0x08
#define XCORDIC_CONTROL_ADDR_ISR        0x0c
#define XCORDIC_CONTROL_ADDR_THETA_DATA 0x10
#define XCORDIC_CONTROL_BITS_THETA_DATA 64
#define XCORDIC_CONTROL_ADDR_S_DATA     0x1c
#define XCORDIC_CONTROL_BITS_S_DATA     64
#define XCORDIC_CONTROL_ADDR_C_DATA     0x28
#define XCORDIC_CONTROL_BITS_C_DATA     64

