// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "update_knn.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic update_knn::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic update_knn::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> update_knn::ap_ST_fsm_state1 = "1";
const sc_lv<4> update_knn::ap_ST_fsm_state2 = "10";
const sc_lv<4> update_knn::ap_ST_fsm_state3 = "100";
const sc_lv<4> update_knn::ap_ST_fsm_state4 = "1000";
const sc_lv<32> update_knn::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> update_knn::ap_const_lv32_1 = "1";
const sc_lv<32> update_knn::ap_const_lv32_2 = "10";
const sc_lv<32> update_knn::ap_const_lv32_3 = "11";
const sc_lv<1> update_knn::ap_const_lv1_1 = "1";
const sc_lv<6> update_knn::ap_const_lv6_1 = "1";
const sc_lv<6> update_knn::ap_const_lv6_0 = "000000";
const sc_lv<6> update_knn::ap_const_lv6_2 = "10";
const sc_lv<32> update_knn::ap_const_lv32_4 = "100";
const sc_lv<32> update_knn::ap_const_lv32_5 = "101";
const sc_lv<32> update_knn::ap_const_lv32_6 = "110";
const sc_lv<32> update_knn::ap_const_lv32_7 = "111";
const sc_lv<32> update_knn::ap_const_lv32_8 = "1000";
const sc_lv<32> update_knn::ap_const_lv32_9 = "1001";
const sc_lv<32> update_knn::ap_const_lv32_A = "1010";
const sc_lv<32> update_knn::ap_const_lv32_B = "1011";
const sc_lv<32> update_knn::ap_const_lv32_C = "1100";
const sc_lv<32> update_knn::ap_const_lv32_D = "1101";
const sc_lv<32> update_knn::ap_const_lv32_E = "1110";
const sc_lv<32> update_knn::ap_const_lv32_F = "1111";
const sc_lv<32> update_knn::ap_const_lv32_10 = "10000";
const sc_lv<32> update_knn::ap_const_lv32_11 = "10001";
const sc_lv<32> update_knn::ap_const_lv32_12 = "10010";
const sc_lv<32> update_knn::ap_const_lv32_13 = "10011";
const sc_lv<32> update_knn::ap_const_lv32_14 = "10100";
const sc_lv<32> update_knn::ap_const_lv32_15 = "10101";
const sc_lv<32> update_knn::ap_const_lv32_16 = "10110";
const sc_lv<32> update_knn::ap_const_lv32_17 = "10111";
const sc_lv<32> update_knn::ap_const_lv32_18 = "11000";
const sc_lv<32> update_knn::ap_const_lv32_19 = "11001";
const sc_lv<32> update_knn::ap_const_lv32_1A = "11010";
const sc_lv<32> update_knn::ap_const_lv32_1B = "11011";
const sc_lv<32> update_knn::ap_const_lv32_1C = "11100";
const sc_lv<32> update_knn::ap_const_lv32_1D = "11101";
const sc_lv<32> update_knn::ap_const_lv32_1E = "11110";
const sc_lv<32> update_knn::ap_const_lv32_1F = "11111";
const sc_lv<32> update_knn::ap_const_lv32_20 = "100000";
const sc_lv<32> update_knn::ap_const_lv32_21 = "100001";
const sc_lv<32> update_knn::ap_const_lv32_22 = "100010";
const sc_lv<32> update_knn::ap_const_lv32_23 = "100011";
const sc_lv<32> update_knn::ap_const_lv32_24 = "100100";
const sc_lv<32> update_knn::ap_const_lv32_25 = "100101";
const sc_lv<32> update_knn::ap_const_lv32_26 = "100110";
const sc_lv<32> update_knn::ap_const_lv32_27 = "100111";
const sc_lv<32> update_knn::ap_const_lv32_28 = "101000";
const sc_lv<32> update_knn::ap_const_lv32_29 = "101001";
const sc_lv<32> update_knn::ap_const_lv32_2A = "101010";
const sc_lv<32> update_knn::ap_const_lv32_2B = "101011";
const sc_lv<32> update_knn::ap_const_lv32_2C = "101100";
const sc_lv<32> update_knn::ap_const_lv32_2D = "101101";
const sc_lv<32> update_knn::ap_const_lv32_2E = "101110";
const sc_lv<32> update_knn::ap_const_lv32_2F = "101111";
const sc_lv<32> update_knn::ap_const_lv32_30 = "110000";
const sc_lv<3> update_knn::ap_const_lv3_4 = "100";
const sc_lv<3> update_knn::ap_const_lv3_0 = "000";
const sc_lv<3> update_knn::ap_const_lv3_2 = "10";
const sc_lv<3> update_knn::ap_const_lv3_1 = "1";
const bool update_knn::ap_const_boolean_1 = true;

update_knn::update_knn(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_dist_V_s_fu_1263_p2);
    sensitive << ( tmp47_cast_fu_1257_p1 );
    sensitive << ( tmp70_cast_fu_1260_p1 );

    SC_METHOD(thread_grp_fu_198_p2);
    sensitive << ( min_distances_V_q0 );
    sensitive << ( min_distances_V_q1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_max_dist_id_1_1_cast_cast_fu_1277_p3);
    sensitive << ( tmp_6_2_reg_1382 );

    SC_METHOD(thread_min_distances_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( min_distances_V_offset );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( p_018_1_1_cast_fu_239_p1 );
    sensitive << ( min_distances_V_load_2_018_1_1_cast_fu_1252_p1 );

    SC_METHOD(thread_min_distances_V_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sum_1_cast_fu_214_p1 );
    sensitive << ( sum_2_cast_fu_249_p1 );
    sensitive << ( sum2_cast_fu_1311_p1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_min_distances_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_min_distances_V_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_min_distances_V_d1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( dist_V_s_fu_1263_p2 );

    SC_METHOD(thread_min_distances_V_load_2_018_1_1_cast_fu_1252_p1);
    sensitive << ( min_distances_V_load_2_018_1_1_fu_1245_p3 );

    SC_METHOD(thread_min_distances_V_load_2_018_1_1_fu_1245_p3);
    sensitive << ( grp_fu_198_p2 );
    sensitive << ( p_018_1_1_reg_1352 );
    sensitive << ( sum_2_cast_cast_fu_1242_p1 );

    SC_METHOD(thread_min_distances_V_we1);
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_4_fu_1296_p2 );

    SC_METHOD(thread_p_018_1_1_cast_fu_239_p1);
    sensitive << ( p_018_1_1_fu_232_p3 );

    SC_METHOD(thread_p_018_1_1_fu_232_p3);
    sensitive << ( tmp_53_reg_1337 );
    sensitive << ( grp_fu_198_p2 );
    sensitive << ( sum_1_cast_cast_fu_229_p1 );

    SC_METHOD(thread_p_max_dist_id_1_1_fu_1288_p3);
    sensitive << ( tmp_1_fu_1284_p2 );
    sensitive << ( max_dist_id_1_1_cast_cast_fu_1277_p3 );
    sensitive << ( p_s_fu_1270_p3 );

    SC_METHOD(thread_p_s_fu_1270_p3);
    sensitive << ( tmp_s_reg_1342 );

    SC_METHOD(thread_r_V_fu_254_p2);
    sensitive << ( ap_port_reg_test_inst_V );
    sensitive << ( ap_port_reg_train_inst_V );

    SC_METHOD(thread_sum2_cast_fu_1311_p1);
    sensitive << ( sum2_fu_1306_p2 );

    SC_METHOD(thread_sum2_fu_1306_p2);
    sensitive << ( tmp_52_reg_1321 );
    sensitive << ( tmp_7_cast_fu_1302_p1 );

    SC_METHOD(thread_sum_1_cast_cast_fu_229_p1);
    sensitive << ( sum_1_reg_1327 );

    SC_METHOD(thread_sum_1_cast_fu_214_p1);
    sensitive << ( sum_1_fu_208_p2 );

    SC_METHOD(thread_sum_1_fu_208_p2);
    sensitive << ( tmp_52_fu_204_p1 );

    SC_METHOD(thread_sum_2_cast_cast_fu_1242_p1);
    sensitive << ( sum_2_reg_1362 );

    SC_METHOD(thread_sum_2_cast_fu_249_p1);
    sensitive << ( sum_2_fu_244_p2 );

    SC_METHOD(thread_sum_2_fu_244_p2);
    sensitive << ( tmp_52_reg_1321 );

    SC_METHOD(thread_tmp10_fu_928_p2);
    sensitive << ( tmp49_cast_fu_882_p1 );
    sensitive << ( tmp54_cast_fu_924_p1 );

    SC_METHOD(thread_tmp11_fu_938_p2);
    sensitive << ( tmp_25_cast_fu_564_p1 );
    sensitive << ( tmp_26_cast_fu_576_p1 );

    SC_METHOD(thread_tmp12_fu_944_p2);
    sensitive << ( tmp_24_cast_fu_552_p1 );
    sensitive << ( tmp11_fu_938_p2 );

    SC_METHOD(thread_tmp13_fu_954_p2);
    sensitive << ( tmp_28_cast_fu_600_p1 );
    sensitive << ( tmp_29_cast_fu_612_p1 );

    SC_METHOD(thread_tmp14_fu_960_p2);
    sensitive << ( tmp_27_cast_fu_588_p1 );
    sensitive << ( tmp13_fu_954_p2 );

    SC_METHOD(thread_tmp15_fu_970_p2);
    sensitive << ( tmp61_cast_fu_950_p1 );
    sensitive << ( tmp63_cast_fu_966_p1 );

    SC_METHOD(thread_tmp16_fu_980_p2);
    sensitive << ( tmp_31_cast_fu_636_p1 );
    sensitive << ( tmp_32_cast_fu_648_p1 );

    SC_METHOD(thread_tmp17_fu_986_p2);
    sensitive << ( tmp_30_cast_fu_624_p1 );
    sensitive << ( tmp16_fu_980_p2 );

    SC_METHOD(thread_tmp18_fu_996_p2);
    sensitive << ( tmp_34_cast_fu_672_p1 );
    sensitive << ( tmp_35_cast_fu_684_p1 );

    SC_METHOD(thread_tmp19_fu_1002_p2);
    sensitive << ( tmp_33_cast_fu_660_p1 );
    sensitive << ( tmp18_fu_996_p2 );

    SC_METHOD(thread_tmp1_fu_850_p2);
    sensitive << ( tmp_46_cast_fu_816_p1 );
    sensitive << ( tmp_fu_844_p2 );

    SC_METHOD(thread_tmp20_fu_1012_p2);
    sensitive << ( tmp66_cast_fu_992_p1 );
    sensitive << ( tmp68_cast_fu_1008_p1 );

    SC_METHOD(thread_tmp21_fu_1022_p2);
    sensitive << ( tmp60_cast_fu_976_p1 );
    sensitive << ( tmp65_cast_fu_1018_p1 );

    SC_METHOD(thread_tmp22_fu_1032_p2);
    sensitive << ( tmp48_cast_fu_934_p1 );
    sensitive << ( tmp59_cast_fu_1028_p1 );

    SC_METHOD(thread_tmp23_fu_1038_p2);
    sensitive << ( tmp_cast_fu_264_p1 );
    sensitive << ( tmp_2_cast_fu_288_p1 );

    SC_METHOD(thread_tmp24_fu_1044_p2);
    sensitive << ( tmp_cast_7_fu_276_p1 );
    sensitive << ( tmp23_fu_1038_p2 );

    SC_METHOD(thread_tmp25_fu_1054_p2);
    sensitive << ( tmp_1_cast_fu_312_p1 );
    sensitive << ( tmp_5_cast_fu_324_p1 );

    SC_METHOD(thread_tmp26_fu_1060_p2);
    sensitive << ( tmp_3_cast_fu_300_p1 );
    sensitive << ( tmp25_fu_1054_p2 );

    SC_METHOD(thread_tmp27_fu_1070_p2);
    sensitive << ( tmp73_cast_fu_1050_p1 );
    sensitive << ( tmp75_cast_fu_1066_p1 );

    SC_METHOD(thread_tmp28_fu_1080_p2);
    sensitive << ( tmp_14_cast_fu_348_p1 );
    sensitive << ( tmp_8_cast_fu_360_p1 );

    SC_METHOD(thread_tmp29_fu_1086_p2);
    sensitive << ( tmp_6_cast_fu_336_p1 );
    sensitive << ( tmp28_fu_1080_p2 );

    SC_METHOD(thread_tmp2_fu_860_p2);
    sensitive << ( tmp_43_cast_fu_780_p1 );
    sensitive << ( tmp_44_cast_fu_792_p1 );

    SC_METHOD(thread_tmp30_fu_1096_p2);
    sensitive << ( tmp_10_cast_fu_384_p1 );
    sensitive << ( tmp_11_cast_fu_396_p1 );

    SC_METHOD(thread_tmp31_fu_1102_p2);
    sensitive << ( tmp_9_cast_fu_372_p1 );
    sensitive << ( tmp30_fu_1096_p2 );

    SC_METHOD(thread_tmp32_fu_1112_p2);
    sensitive << ( tmp78_cast_fu_1092_p1 );
    sensitive << ( tmp80_cast_fu_1108_p1 );

    SC_METHOD(thread_tmp33_fu_1122_p2);
    sensitive << ( tmp72_cast_fu_1076_p1 );
    sensitive << ( tmp77_cast_fu_1118_p1 );

    SC_METHOD(thread_tmp34_fu_1132_p2);
    sensitive << ( tmp_13_cast_fu_420_p1 );
    sensitive << ( tmp_45_cast_fu_432_p1 );

    SC_METHOD(thread_tmp35_fu_1138_p2);
    sensitive << ( tmp_12_cast_fu_408_p1 );
    sensitive << ( tmp34_fu_1132_p2 );

    SC_METHOD(thread_tmp36_fu_1148_p2);
    sensitive << ( tmp_16_cast_fu_456_p1 );
    sensitive << ( tmp_17_cast_fu_468_p1 );

    SC_METHOD(thread_tmp37_fu_1154_p2);
    sensitive << ( tmp_15_cast_fu_444_p1 );
    sensitive << ( tmp36_fu_1148_p2 );

    SC_METHOD(thread_tmp38_fu_1164_p2);
    sensitive << ( tmp84_cast_fu_1144_p1 );
    sensitive << ( tmp86_cast_fu_1160_p1 );

    SC_METHOD(thread_tmp39_fu_1174_p2);
    sensitive << ( tmp_19_cast_fu_492_p1 );
    sensitive << ( tmp_20_cast_fu_504_p1 );

    SC_METHOD(thread_tmp3_fu_866_p2);
    sensitive << ( tmp_42_cast_fu_768_p1 );
    sensitive << ( tmp2_fu_860_p2 );

    SC_METHOD(thread_tmp40_fu_1180_p2);
    sensitive << ( tmp_18_cast_fu_480_p1 );
    sensitive << ( tmp39_fu_1174_p2 );

    SC_METHOD(thread_tmp41_fu_1190_p2);
    sensitive << ( tmp_23_cast_fu_540_p1 );
    sensitive << ( tmp_21_cast_fu_516_p1 );

    SC_METHOD(thread_tmp42_fu_1200_p2);
    sensitive << ( tmp_48_cast_fu_840_p1 );
    sensitive << ( tmp_22_cast_fu_528_p1 );

    SC_METHOD(thread_tmp43_fu_1210_p2);
    sensitive << ( tmp92_cast_fu_1196_p1 );
    sensitive << ( tmp93_cast_fu_1206_p1 );

    SC_METHOD(thread_tmp44_fu_1216_p2);
    sensitive << ( tmp89_cast_fu_1186_p1 );
    sensitive << ( tmp43_fu_1210_p2 );

    SC_METHOD(thread_tmp45_fu_1226_p2);
    sensitive << ( tmp83_cast_fu_1170_p1 );
    sensitive << ( tmp88_cast_fu_1222_p1 );

    SC_METHOD(thread_tmp46_fu_1236_p2);
    sensitive << ( tmp71_cast_fu_1128_p1 );
    sensitive << ( tmp82_cast_fu_1232_p1 );

    SC_METHOD(thread_tmp47_cast_fu_1257_p1);
    sensitive << ( tmp22_reg_1372 );

    SC_METHOD(thread_tmp48_cast_fu_934_p1);
    sensitive << ( tmp10_fu_928_p2 );

    SC_METHOD(thread_tmp49_cast_fu_882_p1);
    sensitive << ( tmp4_fu_876_p2 );

    SC_METHOD(thread_tmp4_fu_876_p2);
    sensitive << ( tmp50_cast_fu_856_p1 );
    sensitive << ( tmp52_cast_fu_872_p1 );

    SC_METHOD(thread_tmp50_cast_fu_856_p1);
    sensitive << ( tmp1_fu_850_p2 );

    SC_METHOD(thread_tmp52_cast_fu_872_p1);
    sensitive << ( tmp3_fu_866_p2 );

    SC_METHOD(thread_tmp54_cast_fu_924_p1);
    sensitive << ( tmp9_fu_918_p2 );

    SC_METHOD(thread_tmp55_cast_fu_898_p1);
    sensitive << ( tmp6_fu_892_p2 );

    SC_METHOD(thread_tmp57_cast_fu_914_p1);
    sensitive << ( tmp8_fu_908_p2 );

    SC_METHOD(thread_tmp59_cast_fu_1028_p1);
    sensitive << ( tmp21_fu_1022_p2 );

    SC_METHOD(thread_tmp5_fu_886_p2);
    sensitive << ( tmp_37_cast_fu_708_p1 );
    sensitive << ( tmp_38_cast_fu_720_p1 );

    SC_METHOD(thread_tmp60_cast_fu_976_p1);
    sensitive << ( tmp15_fu_970_p2 );

    SC_METHOD(thread_tmp61_cast_fu_950_p1);
    sensitive << ( tmp12_fu_944_p2 );

    SC_METHOD(thread_tmp63_cast_fu_966_p1);
    sensitive << ( tmp14_fu_960_p2 );

    SC_METHOD(thread_tmp65_cast_fu_1018_p1);
    sensitive << ( tmp20_fu_1012_p2 );

    SC_METHOD(thread_tmp66_cast_fu_992_p1);
    sensitive << ( tmp17_fu_986_p2 );

    SC_METHOD(thread_tmp68_cast_fu_1008_p1);
    sensitive << ( tmp19_fu_1002_p2 );

    SC_METHOD(thread_tmp6_fu_892_p2);
    sensitive << ( tmp_36_cast_fu_696_p1 );
    sensitive << ( tmp5_fu_886_p2 );

    SC_METHOD(thread_tmp70_cast_fu_1260_p1);
    sensitive << ( tmp46_reg_1377 );

    SC_METHOD(thread_tmp71_cast_fu_1128_p1);
    sensitive << ( tmp33_fu_1122_p2 );

    SC_METHOD(thread_tmp72_cast_fu_1076_p1);
    sensitive << ( tmp27_fu_1070_p2 );

    SC_METHOD(thread_tmp73_cast_fu_1050_p1);
    sensitive << ( tmp24_fu_1044_p2 );

    SC_METHOD(thread_tmp75_cast_fu_1066_p1);
    sensitive << ( tmp26_fu_1060_p2 );

    SC_METHOD(thread_tmp77_cast_fu_1118_p1);
    sensitive << ( tmp32_fu_1112_p2 );

    SC_METHOD(thread_tmp78_cast_fu_1092_p1);
    sensitive << ( tmp29_fu_1086_p2 );

    SC_METHOD(thread_tmp7_fu_902_p2);
    sensitive << ( tmp_40_cast_fu_744_p1 );
    sensitive << ( tmp_41_cast_fu_756_p1 );

    SC_METHOD(thread_tmp80_cast_fu_1108_p1);
    sensitive << ( tmp31_fu_1102_p2 );

    SC_METHOD(thread_tmp82_cast_fu_1232_p1);
    sensitive << ( tmp45_fu_1226_p2 );

    SC_METHOD(thread_tmp83_cast_fu_1170_p1);
    sensitive << ( tmp38_fu_1164_p2 );

    SC_METHOD(thread_tmp84_cast_fu_1144_p1);
    sensitive << ( tmp35_fu_1138_p2 );

    SC_METHOD(thread_tmp86_cast_fu_1160_p1);
    sensitive << ( tmp37_fu_1154_p2 );

    SC_METHOD(thread_tmp88_cast_fu_1222_p1);
    sensitive << ( tmp44_fu_1216_p2 );

    SC_METHOD(thread_tmp89_cast_fu_1186_p1);
    sensitive << ( tmp40_fu_1180_p2 );

    SC_METHOD(thread_tmp8_fu_908_p2);
    sensitive << ( tmp_39_cast_fu_732_p1 );
    sensitive << ( tmp7_fu_902_p2 );

    SC_METHOD(thread_tmp92_cast_fu_1196_p1);
    sensitive << ( tmp41_fu_1190_p2 );

    SC_METHOD(thread_tmp93_cast_fu_1206_p1);
    sensitive << ( tmp42_fu_1200_p2 );

    SC_METHOD(thread_tmp9_fu_918_p2);
    sensitive << ( tmp55_cast_fu_898_p1 );
    sensitive << ( tmp57_cast_fu_914_p1 );

    SC_METHOD(thread_tmp_10_cast_fu_384_p1);
    sensitive << ( tmp_13_fu_376_p3 );

    SC_METHOD(thread_tmp_10_fu_340_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_11_cast_fu_396_p1);
    sensitive << ( tmp_14_fu_388_p3 );

    SC_METHOD(thread_tmp_11_fu_352_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_12_cast_fu_408_p1);
    sensitive << ( tmp_15_fu_400_p3 );

    SC_METHOD(thread_tmp_12_fu_364_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_13_cast_fu_420_p1);
    sensitive << ( tmp_16_fu_412_p3 );

    SC_METHOD(thread_tmp_13_fu_376_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_14_cast_fu_348_p1);
    sensitive << ( tmp_10_fu_340_p3 );

    SC_METHOD(thread_tmp_14_fu_388_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_15_cast_fu_444_p1);
    sensitive << ( tmp_18_fu_436_p3 );

    SC_METHOD(thread_tmp_15_fu_400_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_16_cast_fu_456_p1);
    sensitive << ( tmp_19_fu_448_p3 );

    SC_METHOD(thread_tmp_16_fu_412_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_17_cast_fu_468_p1);
    sensitive << ( tmp_20_fu_460_p3 );

    SC_METHOD(thread_tmp_17_fu_424_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_18_cast_fu_480_p1);
    sensitive << ( tmp_21_fu_472_p3 );

    SC_METHOD(thread_tmp_18_fu_436_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_19_cast_fu_492_p1);
    sensitive << ( tmp_22_fu_484_p3 );

    SC_METHOD(thread_tmp_19_fu_448_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_1_cast_fu_312_p1);
    sensitive << ( tmp_7_fu_304_p3 );

    SC_METHOD(thread_tmp_1_fu_1284_p2);
    sensitive << ( tmp_6_1_reg_1347 );
    sensitive << ( tmp_6_2_reg_1382 );

    SC_METHOD(thread_tmp_20_cast_fu_504_p1);
    sensitive << ( tmp_23_fu_496_p3 );

    SC_METHOD(thread_tmp_20_fu_460_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_21_cast_fu_516_p1);
    sensitive << ( tmp_24_fu_508_p3 );

    SC_METHOD(thread_tmp_21_fu_472_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_22_cast_fu_528_p1);
    sensitive << ( tmp_25_fu_520_p3 );

    SC_METHOD(thread_tmp_22_fu_484_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_23_cast_fu_540_p1);
    sensitive << ( tmp_26_fu_532_p3 );

    SC_METHOD(thread_tmp_23_fu_496_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_24_cast_fu_552_p1);
    sensitive << ( tmp_27_fu_544_p3 );

    SC_METHOD(thread_tmp_24_fu_508_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_25_cast_fu_564_p1);
    sensitive << ( tmp_28_fu_556_p3 );

    SC_METHOD(thread_tmp_25_fu_520_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_26_cast_fu_576_p1);
    sensitive << ( tmp_29_fu_568_p3 );

    SC_METHOD(thread_tmp_26_fu_532_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_27_cast_fu_588_p1);
    sensitive << ( tmp_30_fu_580_p3 );

    SC_METHOD(thread_tmp_27_fu_544_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_28_cast_fu_600_p1);
    sensitive << ( tmp_31_fu_592_p3 );

    SC_METHOD(thread_tmp_28_fu_556_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_29_cast_fu_612_p1);
    sensitive << ( tmp_32_fu_604_p3 );

    SC_METHOD(thread_tmp_29_fu_568_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_2_cast_fu_288_p1);
    sensitive << ( tmp_5_fu_280_p3 );

    SC_METHOD(thread_tmp_2_fu_260_p1);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_30_cast_fu_624_p1);
    sensitive << ( tmp_33_fu_616_p3 );

    SC_METHOD(thread_tmp_30_fu_580_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_31_cast_fu_636_p1);
    sensitive << ( tmp_34_fu_628_p3 );

    SC_METHOD(thread_tmp_31_fu_592_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_32_cast_fu_648_p1);
    sensitive << ( tmp_35_fu_640_p3 );

    SC_METHOD(thread_tmp_32_fu_604_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_33_cast_fu_660_p1);
    sensitive << ( tmp_36_fu_652_p3 );

    SC_METHOD(thread_tmp_33_fu_616_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_34_cast_fu_672_p1);
    sensitive << ( tmp_37_fu_664_p3 );

    SC_METHOD(thread_tmp_34_fu_628_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_35_cast_fu_684_p1);
    sensitive << ( tmp_38_fu_676_p3 );

    SC_METHOD(thread_tmp_35_fu_640_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_36_cast_fu_696_p1);
    sensitive << ( tmp_39_fu_688_p3 );

    SC_METHOD(thread_tmp_36_fu_652_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_37_cast_fu_708_p1);
    sensitive << ( tmp_40_fu_700_p3 );

    SC_METHOD(thread_tmp_37_fu_664_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_38_cast_fu_720_p1);
    sensitive << ( tmp_41_fu_712_p3 );

    SC_METHOD(thread_tmp_38_fu_676_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_39_cast_fu_732_p1);
    sensitive << ( tmp_42_fu_724_p3 );

    SC_METHOD(thread_tmp_39_fu_688_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_3_cast_fu_300_p1);
    sensitive << ( tmp_6_fu_292_p3 );

    SC_METHOD(thread_tmp_3_fu_268_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_40_cast_fu_744_p1);
    sensitive << ( tmp_43_fu_736_p3 );

    SC_METHOD(thread_tmp_40_fu_700_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_41_cast_fu_756_p1);
    sensitive << ( tmp_44_fu_748_p3 );

    SC_METHOD(thread_tmp_41_fu_712_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_42_cast_fu_768_p1);
    sensitive << ( tmp_45_fu_760_p3 );

    SC_METHOD(thread_tmp_42_fu_724_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_43_cast_fu_780_p1);
    sensitive << ( tmp_46_fu_772_p3 );

    SC_METHOD(thread_tmp_43_fu_736_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_44_cast_fu_792_p1);
    sensitive << ( tmp_47_fu_784_p3 );

    SC_METHOD(thread_tmp_44_fu_748_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_45_cast_fu_432_p1);
    sensitive << ( tmp_17_fu_424_p3 );

    SC_METHOD(thread_tmp_45_fu_760_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_46_cast_fu_816_p1);
    sensitive << ( tmp_49_fu_808_p3 );

    SC_METHOD(thread_tmp_46_fu_772_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_47_cast_fu_828_p1);
    sensitive << ( tmp_50_fu_820_p3 );

    SC_METHOD(thread_tmp_47_fu_784_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_48_cast_fu_840_p1);
    sensitive << ( tmp_51_fu_832_p3 );

    SC_METHOD(thread_tmp_48_fu_796_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_49_cast_fu_804_p1);
    sensitive << ( tmp_48_fu_796_p3 );

    SC_METHOD(thread_tmp_49_fu_808_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_4_fu_1296_p2);
    sensitive << ( min_distances_V_q0 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( dist_V_s_fu_1263_p2 );

    SC_METHOD(thread_tmp_50_fu_820_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_51_fu_832_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_52_fu_204_p1);
    sensitive << ( min_distances_V_offset );

    SC_METHOD(thread_tmp_53_fu_219_p1);
    sensitive << ( min_distances_V_offset );

    SC_METHOD(thread_tmp_5_cast_fu_324_p1);
    sensitive << ( tmp_8_fu_316_p3 );

    SC_METHOD(thread_tmp_5_fu_280_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_6_cast_fu_336_p1);
    sensitive << ( tmp_9_fu_328_p3 );

    SC_METHOD(thread_tmp_6_fu_292_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_7_cast_fu_1302_p1);
    sensitive << ( p_max_dist_id_1_1_fu_1288_p3 );

    SC_METHOD(thread_tmp_7_fu_304_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_8_cast_fu_360_p1);
    sensitive << ( tmp_11_fu_352_p3 );

    SC_METHOD(thread_tmp_8_fu_316_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_9_cast_fu_372_p1);
    sensitive << ( tmp_12_fu_364_p3 );

    SC_METHOD(thread_tmp_9_fu_328_p3);
    sensitive << ( r_V_fu_254_p2 );

    SC_METHOD(thread_tmp_cast_7_fu_276_p1);
    sensitive << ( tmp_3_fu_268_p3 );

    SC_METHOD(thread_tmp_cast_fu_264_p1);
    sensitive << ( tmp_2_fu_260_p1 );

    SC_METHOD(thread_tmp_fu_844_p2);
    sensitive << ( tmp_49_cast_fu_804_p1 );
    sensitive << ( tmp_47_cast_fu_828_p1 );

    SC_METHOD(thread_tmp_s_fu_223_p2);
    sensitive << ( min_distances_V_q0 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    ap_CS_fsm = "0001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "update_knn_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, test_inst_V, "(port)test_inst_V");
    sc_trace(mVcdFile, train_inst_V, "(port)train_inst_V");
    sc_trace(mVcdFile, min_distances_V_address0, "(port)min_distances_V_address0");
    sc_trace(mVcdFile, min_distances_V_ce0, "(port)min_distances_V_ce0");
    sc_trace(mVcdFile, min_distances_V_q0, "(port)min_distances_V_q0");
    sc_trace(mVcdFile, min_distances_V_address1, "(port)min_distances_V_address1");
    sc_trace(mVcdFile, min_distances_V_ce1, "(port)min_distances_V_ce1");
    sc_trace(mVcdFile, min_distances_V_we1, "(port)min_distances_V_we1");
    sc_trace(mVcdFile, min_distances_V_d1, "(port)min_distances_V_d1");
    sc_trace(mVcdFile, min_distances_V_q1, "(port)min_distances_V_q1");
    sc_trace(mVcdFile, min_distances_V_offset, "(port)min_distances_V_offset");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_52_fu_204_p1, "tmp_52_fu_204_p1");
    sc_trace(mVcdFile, tmp_52_reg_1321, "tmp_52_reg_1321");
    sc_trace(mVcdFile, sum_1_fu_208_p2, "sum_1_fu_208_p2");
    sc_trace(mVcdFile, sum_1_reg_1327, "sum_1_reg_1327");
    sc_trace(mVcdFile, tmp_53_fu_219_p1, "tmp_53_fu_219_p1");
    sc_trace(mVcdFile, tmp_53_reg_1337, "tmp_53_reg_1337");
    sc_trace(mVcdFile, tmp_s_fu_223_p2, "tmp_s_fu_223_p2");
    sc_trace(mVcdFile, tmp_s_reg_1342, "tmp_s_reg_1342");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_fu_198_p2, "grp_fu_198_p2");
    sc_trace(mVcdFile, tmp_6_1_reg_1347, "tmp_6_1_reg_1347");
    sc_trace(mVcdFile, p_018_1_1_fu_232_p3, "p_018_1_1_fu_232_p3");
    sc_trace(mVcdFile, p_018_1_1_reg_1352, "p_018_1_1_reg_1352");
    sc_trace(mVcdFile, sum_2_fu_244_p2, "sum_2_fu_244_p2");
    sc_trace(mVcdFile, sum_2_reg_1362, "sum_2_reg_1362");
    sc_trace(mVcdFile, tmp22_fu_1032_p2, "tmp22_fu_1032_p2");
    sc_trace(mVcdFile, tmp22_reg_1372, "tmp22_reg_1372");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp46_fu_1236_p2, "tmp46_fu_1236_p2");
    sc_trace(mVcdFile, tmp46_reg_1377, "tmp46_reg_1377");
    sc_trace(mVcdFile, tmp_6_2_reg_1382, "tmp_6_2_reg_1382");
    sc_trace(mVcdFile, ap_port_reg_test_inst_V, "ap_port_reg_test_inst_V");
    sc_trace(mVcdFile, ap_port_reg_train_inst_V, "ap_port_reg_train_inst_V");
    sc_trace(mVcdFile, sum_1_cast_fu_214_p1, "sum_1_cast_fu_214_p1");
    sc_trace(mVcdFile, p_018_1_1_cast_fu_239_p1, "p_018_1_1_cast_fu_239_p1");
    sc_trace(mVcdFile, sum_2_cast_fu_249_p1, "sum_2_cast_fu_249_p1");
    sc_trace(mVcdFile, min_distances_V_load_2_018_1_1_cast_fu_1252_p1, "min_distances_V_load_2_018_1_1_cast_fu_1252_p1");
    sc_trace(mVcdFile, sum2_cast_fu_1311_p1, "sum2_cast_fu_1311_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_4_fu_1296_p2, "tmp_4_fu_1296_p2");
    sc_trace(mVcdFile, dist_V_s_fu_1263_p2, "dist_V_s_fu_1263_p2");
    sc_trace(mVcdFile, sum_1_cast_cast_fu_229_p1, "sum_1_cast_cast_fu_229_p1");
    sc_trace(mVcdFile, r_V_fu_254_p2, "r_V_fu_254_p2");
    sc_trace(mVcdFile, tmp_2_fu_260_p1, "tmp_2_fu_260_p1");
    sc_trace(mVcdFile, tmp_3_fu_268_p3, "tmp_3_fu_268_p3");
    sc_trace(mVcdFile, tmp_5_fu_280_p3, "tmp_5_fu_280_p3");
    sc_trace(mVcdFile, tmp_6_fu_292_p3, "tmp_6_fu_292_p3");
    sc_trace(mVcdFile, tmp_7_fu_304_p3, "tmp_7_fu_304_p3");
    sc_trace(mVcdFile, tmp_8_fu_316_p3, "tmp_8_fu_316_p3");
    sc_trace(mVcdFile, tmp_9_fu_328_p3, "tmp_9_fu_328_p3");
    sc_trace(mVcdFile, tmp_10_fu_340_p3, "tmp_10_fu_340_p3");
    sc_trace(mVcdFile, tmp_11_fu_352_p3, "tmp_11_fu_352_p3");
    sc_trace(mVcdFile, tmp_12_fu_364_p3, "tmp_12_fu_364_p3");
    sc_trace(mVcdFile, tmp_13_fu_376_p3, "tmp_13_fu_376_p3");
    sc_trace(mVcdFile, tmp_14_fu_388_p3, "tmp_14_fu_388_p3");
    sc_trace(mVcdFile, tmp_15_fu_400_p3, "tmp_15_fu_400_p3");
    sc_trace(mVcdFile, tmp_16_fu_412_p3, "tmp_16_fu_412_p3");
    sc_trace(mVcdFile, tmp_17_fu_424_p3, "tmp_17_fu_424_p3");
    sc_trace(mVcdFile, tmp_18_fu_436_p3, "tmp_18_fu_436_p3");
    sc_trace(mVcdFile, tmp_19_fu_448_p3, "tmp_19_fu_448_p3");
    sc_trace(mVcdFile, tmp_20_fu_460_p3, "tmp_20_fu_460_p3");
    sc_trace(mVcdFile, tmp_21_fu_472_p3, "tmp_21_fu_472_p3");
    sc_trace(mVcdFile, tmp_22_fu_484_p3, "tmp_22_fu_484_p3");
    sc_trace(mVcdFile, tmp_23_fu_496_p3, "tmp_23_fu_496_p3");
    sc_trace(mVcdFile, tmp_24_fu_508_p3, "tmp_24_fu_508_p3");
    sc_trace(mVcdFile, tmp_25_fu_520_p3, "tmp_25_fu_520_p3");
    sc_trace(mVcdFile, tmp_26_fu_532_p3, "tmp_26_fu_532_p3");
    sc_trace(mVcdFile, tmp_27_fu_544_p3, "tmp_27_fu_544_p3");
    sc_trace(mVcdFile, tmp_28_fu_556_p3, "tmp_28_fu_556_p3");
    sc_trace(mVcdFile, tmp_29_fu_568_p3, "tmp_29_fu_568_p3");
    sc_trace(mVcdFile, tmp_30_fu_580_p3, "tmp_30_fu_580_p3");
    sc_trace(mVcdFile, tmp_31_fu_592_p3, "tmp_31_fu_592_p3");
    sc_trace(mVcdFile, tmp_32_fu_604_p3, "tmp_32_fu_604_p3");
    sc_trace(mVcdFile, tmp_33_fu_616_p3, "tmp_33_fu_616_p3");
    sc_trace(mVcdFile, tmp_34_fu_628_p3, "tmp_34_fu_628_p3");
    sc_trace(mVcdFile, tmp_35_fu_640_p3, "tmp_35_fu_640_p3");
    sc_trace(mVcdFile, tmp_36_fu_652_p3, "tmp_36_fu_652_p3");
    sc_trace(mVcdFile, tmp_37_fu_664_p3, "tmp_37_fu_664_p3");
    sc_trace(mVcdFile, tmp_38_fu_676_p3, "tmp_38_fu_676_p3");
    sc_trace(mVcdFile, tmp_39_fu_688_p3, "tmp_39_fu_688_p3");
    sc_trace(mVcdFile, tmp_40_fu_700_p3, "tmp_40_fu_700_p3");
    sc_trace(mVcdFile, tmp_41_fu_712_p3, "tmp_41_fu_712_p3");
    sc_trace(mVcdFile, tmp_42_fu_724_p3, "tmp_42_fu_724_p3");
    sc_trace(mVcdFile, tmp_43_fu_736_p3, "tmp_43_fu_736_p3");
    sc_trace(mVcdFile, tmp_44_fu_748_p3, "tmp_44_fu_748_p3");
    sc_trace(mVcdFile, tmp_45_fu_760_p3, "tmp_45_fu_760_p3");
    sc_trace(mVcdFile, tmp_46_fu_772_p3, "tmp_46_fu_772_p3");
    sc_trace(mVcdFile, tmp_47_fu_784_p3, "tmp_47_fu_784_p3");
    sc_trace(mVcdFile, tmp_48_fu_796_p3, "tmp_48_fu_796_p3");
    sc_trace(mVcdFile, tmp_49_fu_808_p3, "tmp_49_fu_808_p3");
    sc_trace(mVcdFile, tmp_50_fu_820_p3, "tmp_50_fu_820_p3");
    sc_trace(mVcdFile, tmp_51_fu_832_p3, "tmp_51_fu_832_p3");
    sc_trace(mVcdFile, tmp_49_cast_fu_804_p1, "tmp_49_cast_fu_804_p1");
    sc_trace(mVcdFile, tmp_47_cast_fu_828_p1, "tmp_47_cast_fu_828_p1");
    sc_trace(mVcdFile, tmp_46_cast_fu_816_p1, "tmp_46_cast_fu_816_p1");
    sc_trace(mVcdFile, tmp_fu_844_p2, "tmp_fu_844_p2");
    sc_trace(mVcdFile, tmp1_fu_850_p2, "tmp1_fu_850_p2");
    sc_trace(mVcdFile, tmp_43_cast_fu_780_p1, "tmp_43_cast_fu_780_p1");
    sc_trace(mVcdFile, tmp_44_cast_fu_792_p1, "tmp_44_cast_fu_792_p1");
    sc_trace(mVcdFile, tmp_42_cast_fu_768_p1, "tmp_42_cast_fu_768_p1");
    sc_trace(mVcdFile, tmp2_fu_860_p2, "tmp2_fu_860_p2");
    sc_trace(mVcdFile, tmp3_fu_866_p2, "tmp3_fu_866_p2");
    sc_trace(mVcdFile, tmp50_cast_fu_856_p1, "tmp50_cast_fu_856_p1");
    sc_trace(mVcdFile, tmp52_cast_fu_872_p1, "tmp52_cast_fu_872_p1");
    sc_trace(mVcdFile, tmp4_fu_876_p2, "tmp4_fu_876_p2");
    sc_trace(mVcdFile, tmp_37_cast_fu_708_p1, "tmp_37_cast_fu_708_p1");
    sc_trace(mVcdFile, tmp_38_cast_fu_720_p1, "tmp_38_cast_fu_720_p1");
    sc_trace(mVcdFile, tmp_36_cast_fu_696_p1, "tmp_36_cast_fu_696_p1");
    sc_trace(mVcdFile, tmp5_fu_886_p2, "tmp5_fu_886_p2");
    sc_trace(mVcdFile, tmp6_fu_892_p2, "tmp6_fu_892_p2");
    sc_trace(mVcdFile, tmp_40_cast_fu_744_p1, "tmp_40_cast_fu_744_p1");
    sc_trace(mVcdFile, tmp_41_cast_fu_756_p1, "tmp_41_cast_fu_756_p1");
    sc_trace(mVcdFile, tmp_39_cast_fu_732_p1, "tmp_39_cast_fu_732_p1");
    sc_trace(mVcdFile, tmp7_fu_902_p2, "tmp7_fu_902_p2");
    sc_trace(mVcdFile, tmp8_fu_908_p2, "tmp8_fu_908_p2");
    sc_trace(mVcdFile, tmp55_cast_fu_898_p1, "tmp55_cast_fu_898_p1");
    sc_trace(mVcdFile, tmp57_cast_fu_914_p1, "tmp57_cast_fu_914_p1");
    sc_trace(mVcdFile, tmp9_fu_918_p2, "tmp9_fu_918_p2");
    sc_trace(mVcdFile, tmp49_cast_fu_882_p1, "tmp49_cast_fu_882_p1");
    sc_trace(mVcdFile, tmp54_cast_fu_924_p1, "tmp54_cast_fu_924_p1");
    sc_trace(mVcdFile, tmp10_fu_928_p2, "tmp10_fu_928_p2");
    sc_trace(mVcdFile, tmp_25_cast_fu_564_p1, "tmp_25_cast_fu_564_p1");
    sc_trace(mVcdFile, tmp_26_cast_fu_576_p1, "tmp_26_cast_fu_576_p1");
    sc_trace(mVcdFile, tmp_24_cast_fu_552_p1, "tmp_24_cast_fu_552_p1");
    sc_trace(mVcdFile, tmp11_fu_938_p2, "tmp11_fu_938_p2");
    sc_trace(mVcdFile, tmp12_fu_944_p2, "tmp12_fu_944_p2");
    sc_trace(mVcdFile, tmp_28_cast_fu_600_p1, "tmp_28_cast_fu_600_p1");
    sc_trace(mVcdFile, tmp_29_cast_fu_612_p1, "tmp_29_cast_fu_612_p1");
    sc_trace(mVcdFile, tmp_27_cast_fu_588_p1, "tmp_27_cast_fu_588_p1");
    sc_trace(mVcdFile, tmp13_fu_954_p2, "tmp13_fu_954_p2");
    sc_trace(mVcdFile, tmp14_fu_960_p2, "tmp14_fu_960_p2");
    sc_trace(mVcdFile, tmp61_cast_fu_950_p1, "tmp61_cast_fu_950_p1");
    sc_trace(mVcdFile, tmp63_cast_fu_966_p1, "tmp63_cast_fu_966_p1");
    sc_trace(mVcdFile, tmp15_fu_970_p2, "tmp15_fu_970_p2");
    sc_trace(mVcdFile, tmp_31_cast_fu_636_p1, "tmp_31_cast_fu_636_p1");
    sc_trace(mVcdFile, tmp_32_cast_fu_648_p1, "tmp_32_cast_fu_648_p1");
    sc_trace(mVcdFile, tmp_30_cast_fu_624_p1, "tmp_30_cast_fu_624_p1");
    sc_trace(mVcdFile, tmp16_fu_980_p2, "tmp16_fu_980_p2");
    sc_trace(mVcdFile, tmp17_fu_986_p2, "tmp17_fu_986_p2");
    sc_trace(mVcdFile, tmp_34_cast_fu_672_p1, "tmp_34_cast_fu_672_p1");
    sc_trace(mVcdFile, tmp_35_cast_fu_684_p1, "tmp_35_cast_fu_684_p1");
    sc_trace(mVcdFile, tmp_33_cast_fu_660_p1, "tmp_33_cast_fu_660_p1");
    sc_trace(mVcdFile, tmp18_fu_996_p2, "tmp18_fu_996_p2");
    sc_trace(mVcdFile, tmp19_fu_1002_p2, "tmp19_fu_1002_p2");
    sc_trace(mVcdFile, tmp66_cast_fu_992_p1, "tmp66_cast_fu_992_p1");
    sc_trace(mVcdFile, tmp68_cast_fu_1008_p1, "tmp68_cast_fu_1008_p1");
    sc_trace(mVcdFile, tmp20_fu_1012_p2, "tmp20_fu_1012_p2");
    sc_trace(mVcdFile, tmp60_cast_fu_976_p1, "tmp60_cast_fu_976_p1");
    sc_trace(mVcdFile, tmp65_cast_fu_1018_p1, "tmp65_cast_fu_1018_p1");
    sc_trace(mVcdFile, tmp21_fu_1022_p2, "tmp21_fu_1022_p2");
    sc_trace(mVcdFile, tmp48_cast_fu_934_p1, "tmp48_cast_fu_934_p1");
    sc_trace(mVcdFile, tmp59_cast_fu_1028_p1, "tmp59_cast_fu_1028_p1");
    sc_trace(mVcdFile, tmp_cast_fu_264_p1, "tmp_cast_fu_264_p1");
    sc_trace(mVcdFile, tmp_2_cast_fu_288_p1, "tmp_2_cast_fu_288_p1");
    sc_trace(mVcdFile, tmp_cast_7_fu_276_p1, "tmp_cast_7_fu_276_p1");
    sc_trace(mVcdFile, tmp23_fu_1038_p2, "tmp23_fu_1038_p2");
    sc_trace(mVcdFile, tmp24_fu_1044_p2, "tmp24_fu_1044_p2");
    sc_trace(mVcdFile, tmp_1_cast_fu_312_p1, "tmp_1_cast_fu_312_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_324_p1, "tmp_5_cast_fu_324_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_300_p1, "tmp_3_cast_fu_300_p1");
    sc_trace(mVcdFile, tmp25_fu_1054_p2, "tmp25_fu_1054_p2");
    sc_trace(mVcdFile, tmp26_fu_1060_p2, "tmp26_fu_1060_p2");
    sc_trace(mVcdFile, tmp73_cast_fu_1050_p1, "tmp73_cast_fu_1050_p1");
    sc_trace(mVcdFile, tmp75_cast_fu_1066_p1, "tmp75_cast_fu_1066_p1");
    sc_trace(mVcdFile, tmp27_fu_1070_p2, "tmp27_fu_1070_p2");
    sc_trace(mVcdFile, tmp_14_cast_fu_348_p1, "tmp_14_cast_fu_348_p1");
    sc_trace(mVcdFile, tmp_8_cast_fu_360_p1, "tmp_8_cast_fu_360_p1");
    sc_trace(mVcdFile, tmp_6_cast_fu_336_p1, "tmp_6_cast_fu_336_p1");
    sc_trace(mVcdFile, tmp28_fu_1080_p2, "tmp28_fu_1080_p2");
    sc_trace(mVcdFile, tmp29_fu_1086_p2, "tmp29_fu_1086_p2");
    sc_trace(mVcdFile, tmp_10_cast_fu_384_p1, "tmp_10_cast_fu_384_p1");
    sc_trace(mVcdFile, tmp_11_cast_fu_396_p1, "tmp_11_cast_fu_396_p1");
    sc_trace(mVcdFile, tmp_9_cast_fu_372_p1, "tmp_9_cast_fu_372_p1");
    sc_trace(mVcdFile, tmp30_fu_1096_p2, "tmp30_fu_1096_p2");
    sc_trace(mVcdFile, tmp31_fu_1102_p2, "tmp31_fu_1102_p2");
    sc_trace(mVcdFile, tmp78_cast_fu_1092_p1, "tmp78_cast_fu_1092_p1");
    sc_trace(mVcdFile, tmp80_cast_fu_1108_p1, "tmp80_cast_fu_1108_p1");
    sc_trace(mVcdFile, tmp32_fu_1112_p2, "tmp32_fu_1112_p2");
    sc_trace(mVcdFile, tmp72_cast_fu_1076_p1, "tmp72_cast_fu_1076_p1");
    sc_trace(mVcdFile, tmp77_cast_fu_1118_p1, "tmp77_cast_fu_1118_p1");
    sc_trace(mVcdFile, tmp33_fu_1122_p2, "tmp33_fu_1122_p2");
    sc_trace(mVcdFile, tmp_13_cast_fu_420_p1, "tmp_13_cast_fu_420_p1");
    sc_trace(mVcdFile, tmp_45_cast_fu_432_p1, "tmp_45_cast_fu_432_p1");
    sc_trace(mVcdFile, tmp_12_cast_fu_408_p1, "tmp_12_cast_fu_408_p1");
    sc_trace(mVcdFile, tmp34_fu_1132_p2, "tmp34_fu_1132_p2");
    sc_trace(mVcdFile, tmp35_fu_1138_p2, "tmp35_fu_1138_p2");
    sc_trace(mVcdFile, tmp_16_cast_fu_456_p1, "tmp_16_cast_fu_456_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_468_p1, "tmp_17_cast_fu_468_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_444_p1, "tmp_15_cast_fu_444_p1");
    sc_trace(mVcdFile, tmp36_fu_1148_p2, "tmp36_fu_1148_p2");
    sc_trace(mVcdFile, tmp37_fu_1154_p2, "tmp37_fu_1154_p2");
    sc_trace(mVcdFile, tmp84_cast_fu_1144_p1, "tmp84_cast_fu_1144_p1");
    sc_trace(mVcdFile, tmp86_cast_fu_1160_p1, "tmp86_cast_fu_1160_p1");
    sc_trace(mVcdFile, tmp38_fu_1164_p2, "tmp38_fu_1164_p2");
    sc_trace(mVcdFile, tmp_19_cast_fu_492_p1, "tmp_19_cast_fu_492_p1");
    sc_trace(mVcdFile, tmp_20_cast_fu_504_p1, "tmp_20_cast_fu_504_p1");
    sc_trace(mVcdFile, tmp_18_cast_fu_480_p1, "tmp_18_cast_fu_480_p1");
    sc_trace(mVcdFile, tmp39_fu_1174_p2, "tmp39_fu_1174_p2");
    sc_trace(mVcdFile, tmp40_fu_1180_p2, "tmp40_fu_1180_p2");
    sc_trace(mVcdFile, tmp_23_cast_fu_540_p1, "tmp_23_cast_fu_540_p1");
    sc_trace(mVcdFile, tmp_21_cast_fu_516_p1, "tmp_21_cast_fu_516_p1");
    sc_trace(mVcdFile, tmp41_fu_1190_p2, "tmp41_fu_1190_p2");
    sc_trace(mVcdFile, tmp_48_cast_fu_840_p1, "tmp_48_cast_fu_840_p1");
    sc_trace(mVcdFile, tmp_22_cast_fu_528_p1, "tmp_22_cast_fu_528_p1");
    sc_trace(mVcdFile, tmp42_fu_1200_p2, "tmp42_fu_1200_p2");
    sc_trace(mVcdFile, tmp92_cast_fu_1196_p1, "tmp92_cast_fu_1196_p1");
    sc_trace(mVcdFile, tmp93_cast_fu_1206_p1, "tmp93_cast_fu_1206_p1");
    sc_trace(mVcdFile, tmp89_cast_fu_1186_p1, "tmp89_cast_fu_1186_p1");
    sc_trace(mVcdFile, tmp43_fu_1210_p2, "tmp43_fu_1210_p2");
    sc_trace(mVcdFile, tmp44_fu_1216_p2, "tmp44_fu_1216_p2");
    sc_trace(mVcdFile, tmp83_cast_fu_1170_p1, "tmp83_cast_fu_1170_p1");
    sc_trace(mVcdFile, tmp88_cast_fu_1222_p1, "tmp88_cast_fu_1222_p1");
    sc_trace(mVcdFile, tmp45_fu_1226_p2, "tmp45_fu_1226_p2");
    sc_trace(mVcdFile, tmp71_cast_fu_1128_p1, "tmp71_cast_fu_1128_p1");
    sc_trace(mVcdFile, tmp82_cast_fu_1232_p1, "tmp82_cast_fu_1232_p1");
    sc_trace(mVcdFile, sum_2_cast_cast_fu_1242_p1, "sum_2_cast_cast_fu_1242_p1");
    sc_trace(mVcdFile, min_distances_V_load_2_018_1_1_fu_1245_p3, "min_distances_V_load_2_018_1_1_fu_1245_p3");
    sc_trace(mVcdFile, tmp47_cast_fu_1257_p1, "tmp47_cast_fu_1257_p1");
    sc_trace(mVcdFile, tmp70_cast_fu_1260_p1, "tmp70_cast_fu_1260_p1");
    sc_trace(mVcdFile, tmp_1_fu_1284_p2, "tmp_1_fu_1284_p2");
    sc_trace(mVcdFile, max_dist_id_1_1_cast_cast_fu_1277_p3, "max_dist_id_1_1_cast_cast_fu_1277_p3");
    sc_trace(mVcdFile, p_s_fu_1270_p3, "p_s_fu_1270_p3");
    sc_trace(mVcdFile, p_max_dist_id_1_1_fu_1288_p3, "p_max_dist_id_1_1_fu_1288_p3");
    sc_trace(mVcdFile, tmp_7_cast_fu_1302_p1, "tmp_7_cast_fu_1302_p1");
    sc_trace(mVcdFile, sum2_fu_1306_p2, "sum2_fu_1306_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

update_knn::~update_knn() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void update_knn::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        ap_port_reg_test_inst_V = test_inst_V.read();
        ap_port_reg_train_inst_V = train_inst_V.read();
        sum_1_reg_1327 = sum_1_fu_208_p2.read();
        tmp_52_reg_1321 = tmp_52_fu_204_p1.read();
        tmp_53_reg_1337 = tmp_53_fu_219_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        p_018_1_1_reg_1352 = p_018_1_1_fu_232_p3.read();
        sum_2_reg_1362 = sum_2_fu_244_p2.read();
        tmp_6_1_reg_1347 = grp_fu_198_p2.read();
        tmp_s_reg_1342 = tmp_s_fu_223_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        tmp22_reg_1372 = tmp22_fu_1032_p2.read();
        tmp46_reg_1377 = tmp46_fu_1236_p2.read();
        tmp_6_2_reg_1382 = grp_fu_198_p2.read();
    }
}

void update_knn::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void update_knn::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void update_knn::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void update_knn::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void update_knn::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void update_knn::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void update_knn::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void update_knn::thread_dist_V_s_fu_1263_p2() {
    dist_V_s_fu_1263_p2 = (!tmp47_cast_fu_1257_p1.read().is_01() || !tmp70_cast_fu_1260_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp47_cast_fu_1257_p1.read()) + sc_biguint<6>(tmp70_cast_fu_1260_p1.read()));
}

void update_knn::thread_grp_fu_198_p2() {
    grp_fu_198_p2 = (!min_distances_V_q1.read().is_01() || !min_distances_V_q0.read().is_01())? sc_lv<1>(): (sc_biguint<6>(min_distances_V_q1.read()) > sc_biguint<6>(min_distances_V_q0.read()));
}

void update_knn::thread_max_dist_id_1_1_cast_cast_fu_1277_p3() {
    max_dist_id_1_1_cast_cast_fu_1277_p3 = (!tmp_6_2_reg_1382.read()[0].is_01())? sc_lv<3>(): ((tmp_6_2_reg_1382.read()[0].to_bool())? ap_const_lv3_2: ap_const_lv3_1);
}

void update_knn::thread_min_distances_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        min_distances_V_address0 =  (sc_lv<5>) (min_distances_V_load_2_018_1_1_cast_fu_1252_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        min_distances_V_address0 =  (sc_lv<5>) (p_018_1_1_cast_fu_239_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        min_distances_V_address0 =  (sc_lv<5>) (min_distances_V_offset.read());
    } else {
        min_distances_V_address0 = "XXXXX";
    }
}

void update_knn::thread_min_distances_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        min_distances_V_address1 =  (sc_lv<5>) (sum2_cast_fu_1311_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        min_distances_V_address1 =  (sc_lv<5>) (sum_2_cast_fu_249_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        min_distances_V_address1 =  (sc_lv<5>) (sum_1_cast_fu_214_p1.read());
    } else {
        min_distances_V_address1 = "XXXXX";
    }
}

void update_knn::thread_min_distances_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())))) {
        min_distances_V_ce0 = ap_const_logic_1;
    } else {
        min_distances_V_ce0 = ap_const_logic_0;
    }
}

void update_knn::thread_min_distances_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())))) {
        min_distances_V_ce1 = ap_const_logic_1;
    } else {
        min_distances_V_ce1 = ap_const_logic_0;
    }
}

void update_knn::thread_min_distances_V_d1() {
    min_distances_V_d1 = dist_V_s_fu_1263_p2.read();
}

void update_knn::thread_min_distances_V_load_2_018_1_1_cast_fu_1252_p1() {
    min_distances_V_load_2_018_1_1_cast_fu_1252_p1 = esl_zext<64,32>(min_distances_V_load_2_018_1_1_fu_1245_p3.read());
}

void update_knn::thread_min_distances_V_load_2_018_1_1_fu_1245_p3() {
    min_distances_V_load_2_018_1_1_fu_1245_p3 = (!grp_fu_198_p2.read()[0].is_01())? sc_lv<32>(): ((grp_fu_198_p2.read()[0].to_bool())? sum_2_cast_cast_fu_1242_p1.read(): p_018_1_1_reg_1352.read());
}

void update_knn::thread_min_distances_V_we1() {
    if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(tmp_4_fu_1296_p2.read(), ap_const_lv1_1))) {
        min_distances_V_we1 = ap_const_logic_1;
    } else {
        min_distances_V_we1 = ap_const_logic_0;
    }
}

void update_knn::thread_p_018_1_1_cast_fu_239_p1() {
    p_018_1_1_cast_fu_239_p1 = esl_zext<64,32>(p_018_1_1_fu_232_p3.read());
}

void update_knn::thread_p_018_1_1_fu_232_p3() {
    p_018_1_1_fu_232_p3 = (!grp_fu_198_p2.read()[0].is_01())? sc_lv<32>(): ((grp_fu_198_p2.read()[0].to_bool())? sum_1_cast_cast_fu_229_p1.read(): tmp_53_reg_1337.read());
}

void update_knn::thread_p_max_dist_id_1_1_fu_1288_p3() {
    p_max_dist_id_1_1_fu_1288_p3 = (!tmp_1_fu_1284_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_1_fu_1284_p2.read()[0].to_bool())? max_dist_id_1_1_cast_cast_fu_1277_p3.read(): p_s_fu_1270_p3.read());
}

void update_knn::thread_p_s_fu_1270_p3() {
    p_s_fu_1270_p3 = (!tmp_s_reg_1342.read()[0].is_01())? sc_lv<3>(): ((tmp_s_reg_1342.read()[0].to_bool())? ap_const_lv3_4: ap_const_lv3_0);
}

void update_knn::thread_r_V_fu_254_p2() {
    r_V_fu_254_p2 = (ap_port_reg_train_inst_V.read() ^ ap_port_reg_test_inst_V.read());
}

void update_knn::thread_sum2_cast_fu_1311_p1() {
    sum2_cast_fu_1311_p1 = esl_zext<64,6>(sum2_fu_1306_p2.read());
}

void update_knn::thread_sum2_fu_1306_p2() {
    sum2_fu_1306_p2 = (!tmp_7_cast_fu_1302_p1.read().is_01() || !tmp_52_reg_1321.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_7_cast_fu_1302_p1.read()) + sc_biguint<6>(tmp_52_reg_1321.read()));
}

void update_knn::thread_sum_1_cast_cast_fu_229_p1() {
    sum_1_cast_cast_fu_229_p1 = esl_zext<32,6>(sum_1_reg_1327.read());
}

void update_knn::thread_sum_1_cast_fu_214_p1() {
    sum_1_cast_fu_214_p1 = esl_zext<64,6>(sum_1_fu_208_p2.read());
}

void update_knn::thread_sum_1_fu_208_p2() {
    sum_1_fu_208_p2 = (!ap_const_lv6_1.is_01() || !tmp_52_fu_204_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(tmp_52_fu_204_p1.read()));
}

void update_knn::thread_sum_2_cast_cast_fu_1242_p1() {
    sum_2_cast_cast_fu_1242_p1 = esl_zext<32,6>(sum_2_reg_1362.read());
}

void update_knn::thread_sum_2_cast_fu_249_p1() {
    sum_2_cast_fu_249_p1 = esl_zext<64,6>(sum_2_fu_244_p2.read());
}

void update_knn::thread_sum_2_fu_244_p2() {
    sum_2_fu_244_p2 = (!ap_const_lv6_2.is_01() || !tmp_52_reg_1321.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_2) + sc_biguint<6>(tmp_52_reg_1321.read()));
}

void update_knn::thread_tmp10_fu_928_p2() {
    tmp10_fu_928_p2 = (!tmp49_cast_fu_882_p1.read().is_01() || !tmp54_cast_fu_924_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp49_cast_fu_882_p1.read()) + sc_biguint<4>(tmp54_cast_fu_924_p1.read()));
}

void update_knn::thread_tmp11_fu_938_p2() {
    tmp11_fu_938_p2 = (!tmp_25_cast_fu_564_p1.read().is_01() || !tmp_26_cast_fu_576_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_25_cast_fu_564_p1.read()) + sc_biguint<2>(tmp_26_cast_fu_576_p1.read()));
}

void update_knn::thread_tmp12_fu_944_p2() {
    tmp12_fu_944_p2 = (!tmp_24_cast_fu_552_p1.read().is_01() || !tmp11_fu_938_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_24_cast_fu_552_p1.read()) + sc_biguint<2>(tmp11_fu_938_p2.read()));
}

void update_knn::thread_tmp13_fu_954_p2() {
    tmp13_fu_954_p2 = (!tmp_28_cast_fu_600_p1.read().is_01() || !tmp_29_cast_fu_612_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_28_cast_fu_600_p1.read()) + sc_biguint<2>(tmp_29_cast_fu_612_p1.read()));
}

void update_knn::thread_tmp14_fu_960_p2() {
    tmp14_fu_960_p2 = (!tmp_27_cast_fu_588_p1.read().is_01() || !tmp13_fu_954_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_27_cast_fu_588_p1.read()) + sc_biguint<2>(tmp13_fu_954_p2.read()));
}

void update_knn::thread_tmp15_fu_970_p2() {
    tmp15_fu_970_p2 = (!tmp61_cast_fu_950_p1.read().is_01() || !tmp63_cast_fu_966_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp61_cast_fu_950_p1.read()) + sc_biguint<3>(tmp63_cast_fu_966_p1.read()));
}

void update_knn::thread_tmp16_fu_980_p2() {
    tmp16_fu_980_p2 = (!tmp_31_cast_fu_636_p1.read().is_01() || !tmp_32_cast_fu_648_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_31_cast_fu_636_p1.read()) + sc_biguint<2>(tmp_32_cast_fu_648_p1.read()));
}

void update_knn::thread_tmp17_fu_986_p2() {
    tmp17_fu_986_p2 = (!tmp_30_cast_fu_624_p1.read().is_01() || !tmp16_fu_980_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_30_cast_fu_624_p1.read()) + sc_biguint<2>(tmp16_fu_980_p2.read()));
}

void update_knn::thread_tmp18_fu_996_p2() {
    tmp18_fu_996_p2 = (!tmp_34_cast_fu_672_p1.read().is_01() || !tmp_35_cast_fu_684_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_34_cast_fu_672_p1.read()) + sc_biguint<2>(tmp_35_cast_fu_684_p1.read()));
}

void update_knn::thread_tmp19_fu_1002_p2() {
    tmp19_fu_1002_p2 = (!tmp_33_cast_fu_660_p1.read().is_01() || !tmp18_fu_996_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_33_cast_fu_660_p1.read()) + sc_biguint<2>(tmp18_fu_996_p2.read()));
}

void update_knn::thread_tmp1_fu_850_p2() {
    tmp1_fu_850_p2 = (!tmp_46_cast_fu_816_p1.read().is_01() || !tmp_fu_844_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_46_cast_fu_816_p1.read()) + sc_biguint<2>(tmp_fu_844_p2.read()));
}

void update_knn::thread_tmp20_fu_1012_p2() {
    tmp20_fu_1012_p2 = (!tmp66_cast_fu_992_p1.read().is_01() || !tmp68_cast_fu_1008_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp66_cast_fu_992_p1.read()) + sc_biguint<3>(tmp68_cast_fu_1008_p1.read()));
}

void update_knn::thread_tmp21_fu_1022_p2() {
    tmp21_fu_1022_p2 = (!tmp60_cast_fu_976_p1.read().is_01() || !tmp65_cast_fu_1018_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp60_cast_fu_976_p1.read()) + sc_biguint<4>(tmp65_cast_fu_1018_p1.read()));
}

void update_knn::thread_tmp22_fu_1032_p2() {
    tmp22_fu_1032_p2 = (!tmp48_cast_fu_934_p1.read().is_01() || !tmp59_cast_fu_1028_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp48_cast_fu_934_p1.read()) + sc_biguint<5>(tmp59_cast_fu_1028_p1.read()));
}

void update_knn::thread_tmp23_fu_1038_p2() {
    tmp23_fu_1038_p2 = (!tmp_cast_fu_264_p1.read().is_01() || !tmp_2_cast_fu_288_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_cast_fu_264_p1.read()) + sc_biguint<2>(tmp_2_cast_fu_288_p1.read()));
}

void update_knn::thread_tmp24_fu_1044_p2() {
    tmp24_fu_1044_p2 = (!tmp_cast_7_fu_276_p1.read().is_01() || !tmp23_fu_1038_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_cast_7_fu_276_p1.read()) + sc_biguint<2>(tmp23_fu_1038_p2.read()));
}

void update_knn::thread_tmp25_fu_1054_p2() {
    tmp25_fu_1054_p2 = (!tmp_1_cast_fu_312_p1.read().is_01() || !tmp_5_cast_fu_324_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_1_cast_fu_312_p1.read()) + sc_biguint<2>(tmp_5_cast_fu_324_p1.read()));
}

void update_knn::thread_tmp26_fu_1060_p2() {
    tmp26_fu_1060_p2 = (!tmp_3_cast_fu_300_p1.read().is_01() || !tmp25_fu_1054_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_3_cast_fu_300_p1.read()) + sc_biguint<2>(tmp25_fu_1054_p2.read()));
}

void update_knn::thread_tmp27_fu_1070_p2() {
    tmp27_fu_1070_p2 = (!tmp73_cast_fu_1050_p1.read().is_01() || !tmp75_cast_fu_1066_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp73_cast_fu_1050_p1.read()) + sc_biguint<3>(tmp75_cast_fu_1066_p1.read()));
}

void update_knn::thread_tmp28_fu_1080_p2() {
    tmp28_fu_1080_p2 = (!tmp_14_cast_fu_348_p1.read().is_01() || !tmp_8_cast_fu_360_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_14_cast_fu_348_p1.read()) + sc_biguint<2>(tmp_8_cast_fu_360_p1.read()));
}

void update_knn::thread_tmp29_fu_1086_p2() {
    tmp29_fu_1086_p2 = (!tmp_6_cast_fu_336_p1.read().is_01() || !tmp28_fu_1080_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_6_cast_fu_336_p1.read()) + sc_biguint<2>(tmp28_fu_1080_p2.read()));
}

void update_knn::thread_tmp2_fu_860_p2() {
    tmp2_fu_860_p2 = (!tmp_43_cast_fu_780_p1.read().is_01() || !tmp_44_cast_fu_792_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_43_cast_fu_780_p1.read()) + sc_biguint<2>(tmp_44_cast_fu_792_p1.read()));
}

void update_knn::thread_tmp30_fu_1096_p2() {
    tmp30_fu_1096_p2 = (!tmp_10_cast_fu_384_p1.read().is_01() || !tmp_11_cast_fu_396_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_10_cast_fu_384_p1.read()) + sc_biguint<2>(tmp_11_cast_fu_396_p1.read()));
}

void update_knn::thread_tmp31_fu_1102_p2() {
    tmp31_fu_1102_p2 = (!tmp_9_cast_fu_372_p1.read().is_01() || !tmp30_fu_1096_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_9_cast_fu_372_p1.read()) + sc_biguint<2>(tmp30_fu_1096_p2.read()));
}

void update_knn::thread_tmp32_fu_1112_p2() {
    tmp32_fu_1112_p2 = (!tmp78_cast_fu_1092_p1.read().is_01() || !tmp80_cast_fu_1108_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp78_cast_fu_1092_p1.read()) + sc_biguint<3>(tmp80_cast_fu_1108_p1.read()));
}

void update_knn::thread_tmp33_fu_1122_p2() {
    tmp33_fu_1122_p2 = (!tmp72_cast_fu_1076_p1.read().is_01() || !tmp77_cast_fu_1118_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp72_cast_fu_1076_p1.read()) + sc_biguint<4>(tmp77_cast_fu_1118_p1.read()));
}

void update_knn::thread_tmp34_fu_1132_p2() {
    tmp34_fu_1132_p2 = (!tmp_13_cast_fu_420_p1.read().is_01() || !tmp_45_cast_fu_432_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_13_cast_fu_420_p1.read()) + sc_biguint<2>(tmp_45_cast_fu_432_p1.read()));
}

void update_knn::thread_tmp35_fu_1138_p2() {
    tmp35_fu_1138_p2 = (!tmp_12_cast_fu_408_p1.read().is_01() || !tmp34_fu_1132_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_12_cast_fu_408_p1.read()) + sc_biguint<2>(tmp34_fu_1132_p2.read()));
}

void update_knn::thread_tmp36_fu_1148_p2() {
    tmp36_fu_1148_p2 = (!tmp_16_cast_fu_456_p1.read().is_01() || !tmp_17_cast_fu_468_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_16_cast_fu_456_p1.read()) + sc_biguint<2>(tmp_17_cast_fu_468_p1.read()));
}

void update_knn::thread_tmp37_fu_1154_p2() {
    tmp37_fu_1154_p2 = (!tmp_15_cast_fu_444_p1.read().is_01() || !tmp36_fu_1148_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_15_cast_fu_444_p1.read()) + sc_biguint<2>(tmp36_fu_1148_p2.read()));
}

void update_knn::thread_tmp38_fu_1164_p2() {
    tmp38_fu_1164_p2 = (!tmp84_cast_fu_1144_p1.read().is_01() || !tmp86_cast_fu_1160_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp84_cast_fu_1144_p1.read()) + sc_biguint<3>(tmp86_cast_fu_1160_p1.read()));
}

void update_knn::thread_tmp39_fu_1174_p2() {
    tmp39_fu_1174_p2 = (!tmp_19_cast_fu_492_p1.read().is_01() || !tmp_20_cast_fu_504_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_19_cast_fu_492_p1.read()) + sc_biguint<2>(tmp_20_cast_fu_504_p1.read()));
}

void update_knn::thread_tmp3_fu_866_p2() {
    tmp3_fu_866_p2 = (!tmp_42_cast_fu_768_p1.read().is_01() || !tmp2_fu_860_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_42_cast_fu_768_p1.read()) + sc_biguint<2>(tmp2_fu_860_p2.read()));
}

void update_knn::thread_tmp40_fu_1180_p2() {
    tmp40_fu_1180_p2 = (!tmp_18_cast_fu_480_p1.read().is_01() || !tmp39_fu_1174_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_18_cast_fu_480_p1.read()) + sc_biguint<2>(tmp39_fu_1174_p2.read()));
}

void update_knn::thread_tmp41_fu_1190_p2() {
    tmp41_fu_1190_p2 = (!tmp_23_cast_fu_540_p1.read().is_01() || !tmp_21_cast_fu_516_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_23_cast_fu_540_p1.read()) + sc_biguint<2>(tmp_21_cast_fu_516_p1.read()));
}

void update_knn::thread_tmp42_fu_1200_p2() {
    tmp42_fu_1200_p2 = (!tmp_48_cast_fu_840_p1.read().is_01() || !tmp_22_cast_fu_528_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_48_cast_fu_840_p1.read()) + sc_biguint<2>(tmp_22_cast_fu_528_p1.read()));
}

void update_knn::thread_tmp43_fu_1210_p2() {
    tmp43_fu_1210_p2 = (!tmp92_cast_fu_1196_p1.read().is_01() || !tmp93_cast_fu_1206_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp92_cast_fu_1196_p1.read()) + sc_biguint<3>(tmp93_cast_fu_1206_p1.read()));
}

void update_knn::thread_tmp44_fu_1216_p2() {
    tmp44_fu_1216_p2 = (!tmp89_cast_fu_1186_p1.read().is_01() || !tmp43_fu_1210_p2.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp89_cast_fu_1186_p1.read()) + sc_biguint<3>(tmp43_fu_1210_p2.read()));
}

void update_knn::thread_tmp45_fu_1226_p2() {
    tmp45_fu_1226_p2 = (!tmp83_cast_fu_1170_p1.read().is_01() || !tmp88_cast_fu_1222_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp83_cast_fu_1170_p1.read()) + sc_biguint<4>(tmp88_cast_fu_1222_p1.read()));
}

void update_knn::thread_tmp46_fu_1236_p2() {
    tmp46_fu_1236_p2 = (!tmp71_cast_fu_1128_p1.read().is_01() || !tmp82_cast_fu_1232_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp71_cast_fu_1128_p1.read()) + sc_biguint<5>(tmp82_cast_fu_1232_p1.read()));
}

void update_knn::thread_tmp47_cast_fu_1257_p1() {
    tmp47_cast_fu_1257_p1 = esl_zext<6,5>(tmp22_reg_1372.read());
}

void update_knn::thread_tmp48_cast_fu_934_p1() {
    tmp48_cast_fu_934_p1 = esl_zext<5,4>(tmp10_fu_928_p2.read());
}

void update_knn::thread_tmp49_cast_fu_882_p1() {
    tmp49_cast_fu_882_p1 = esl_zext<4,3>(tmp4_fu_876_p2.read());
}

void update_knn::thread_tmp4_fu_876_p2() {
    tmp4_fu_876_p2 = (!tmp50_cast_fu_856_p1.read().is_01() || !tmp52_cast_fu_872_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp50_cast_fu_856_p1.read()) + sc_biguint<3>(tmp52_cast_fu_872_p1.read()));
}

void update_knn::thread_tmp50_cast_fu_856_p1() {
    tmp50_cast_fu_856_p1 = esl_zext<3,2>(tmp1_fu_850_p2.read());
}

void update_knn::thread_tmp52_cast_fu_872_p1() {
    tmp52_cast_fu_872_p1 = esl_zext<3,2>(tmp3_fu_866_p2.read());
}

void update_knn::thread_tmp54_cast_fu_924_p1() {
    tmp54_cast_fu_924_p1 = esl_zext<4,3>(tmp9_fu_918_p2.read());
}

void update_knn::thread_tmp55_cast_fu_898_p1() {
    tmp55_cast_fu_898_p1 = esl_zext<3,2>(tmp6_fu_892_p2.read());
}

void update_knn::thread_tmp57_cast_fu_914_p1() {
    tmp57_cast_fu_914_p1 = esl_zext<3,2>(tmp8_fu_908_p2.read());
}

void update_knn::thread_tmp59_cast_fu_1028_p1() {
    tmp59_cast_fu_1028_p1 = esl_zext<5,4>(tmp21_fu_1022_p2.read());
}

void update_knn::thread_tmp5_fu_886_p2() {
    tmp5_fu_886_p2 = (!tmp_37_cast_fu_708_p1.read().is_01() || !tmp_38_cast_fu_720_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_37_cast_fu_708_p1.read()) + sc_biguint<2>(tmp_38_cast_fu_720_p1.read()));
}

void update_knn::thread_tmp60_cast_fu_976_p1() {
    tmp60_cast_fu_976_p1 = esl_zext<4,3>(tmp15_fu_970_p2.read());
}

void update_knn::thread_tmp61_cast_fu_950_p1() {
    tmp61_cast_fu_950_p1 = esl_zext<3,2>(tmp12_fu_944_p2.read());
}

void update_knn::thread_tmp63_cast_fu_966_p1() {
    tmp63_cast_fu_966_p1 = esl_zext<3,2>(tmp14_fu_960_p2.read());
}

void update_knn::thread_tmp65_cast_fu_1018_p1() {
    tmp65_cast_fu_1018_p1 = esl_zext<4,3>(tmp20_fu_1012_p2.read());
}

void update_knn::thread_tmp66_cast_fu_992_p1() {
    tmp66_cast_fu_992_p1 = esl_zext<3,2>(tmp17_fu_986_p2.read());
}

void update_knn::thread_tmp68_cast_fu_1008_p1() {
    tmp68_cast_fu_1008_p1 = esl_zext<3,2>(tmp19_fu_1002_p2.read());
}

void update_knn::thread_tmp6_fu_892_p2() {
    tmp6_fu_892_p2 = (!tmp_36_cast_fu_696_p1.read().is_01() || !tmp5_fu_886_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_36_cast_fu_696_p1.read()) + sc_biguint<2>(tmp5_fu_886_p2.read()));
}

void update_knn::thread_tmp70_cast_fu_1260_p1() {
    tmp70_cast_fu_1260_p1 = esl_zext<6,5>(tmp46_reg_1377.read());
}

void update_knn::thread_tmp71_cast_fu_1128_p1() {
    tmp71_cast_fu_1128_p1 = esl_zext<5,4>(tmp33_fu_1122_p2.read());
}

void update_knn::thread_tmp72_cast_fu_1076_p1() {
    tmp72_cast_fu_1076_p1 = esl_zext<4,3>(tmp27_fu_1070_p2.read());
}

void update_knn::thread_tmp73_cast_fu_1050_p1() {
    tmp73_cast_fu_1050_p1 = esl_zext<3,2>(tmp24_fu_1044_p2.read());
}

void update_knn::thread_tmp75_cast_fu_1066_p1() {
    tmp75_cast_fu_1066_p1 = esl_zext<3,2>(tmp26_fu_1060_p2.read());
}

void update_knn::thread_tmp77_cast_fu_1118_p1() {
    tmp77_cast_fu_1118_p1 = esl_zext<4,3>(tmp32_fu_1112_p2.read());
}

void update_knn::thread_tmp78_cast_fu_1092_p1() {
    tmp78_cast_fu_1092_p1 = esl_zext<3,2>(tmp29_fu_1086_p2.read());
}

void update_knn::thread_tmp7_fu_902_p2() {
    tmp7_fu_902_p2 = (!tmp_40_cast_fu_744_p1.read().is_01() || !tmp_41_cast_fu_756_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_40_cast_fu_744_p1.read()) + sc_biguint<2>(tmp_41_cast_fu_756_p1.read()));
}

void update_knn::thread_tmp80_cast_fu_1108_p1() {
    tmp80_cast_fu_1108_p1 = esl_zext<3,2>(tmp31_fu_1102_p2.read());
}

void update_knn::thread_tmp82_cast_fu_1232_p1() {
    tmp82_cast_fu_1232_p1 = esl_zext<5,4>(tmp45_fu_1226_p2.read());
}

void update_knn::thread_tmp83_cast_fu_1170_p1() {
    tmp83_cast_fu_1170_p1 = esl_zext<4,3>(tmp38_fu_1164_p2.read());
}

void update_knn::thread_tmp84_cast_fu_1144_p1() {
    tmp84_cast_fu_1144_p1 = esl_zext<3,2>(tmp35_fu_1138_p2.read());
}

void update_knn::thread_tmp86_cast_fu_1160_p1() {
    tmp86_cast_fu_1160_p1 = esl_zext<3,2>(tmp37_fu_1154_p2.read());
}

void update_knn::thread_tmp88_cast_fu_1222_p1() {
    tmp88_cast_fu_1222_p1 = esl_zext<4,3>(tmp44_fu_1216_p2.read());
}

void update_knn::thread_tmp89_cast_fu_1186_p1() {
    tmp89_cast_fu_1186_p1 = esl_zext<3,2>(tmp40_fu_1180_p2.read());
}

void update_knn::thread_tmp8_fu_908_p2() {
    tmp8_fu_908_p2 = (!tmp_39_cast_fu_732_p1.read().is_01() || !tmp7_fu_902_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_39_cast_fu_732_p1.read()) + sc_biguint<2>(tmp7_fu_902_p2.read()));
}

void update_knn::thread_tmp92_cast_fu_1196_p1() {
    tmp92_cast_fu_1196_p1 = esl_zext<3,2>(tmp41_fu_1190_p2.read());
}

void update_knn::thread_tmp93_cast_fu_1206_p1() {
    tmp93_cast_fu_1206_p1 = esl_zext<3,2>(tmp42_fu_1200_p2.read());
}

void update_knn::thread_tmp9_fu_918_p2() {
    tmp9_fu_918_p2 = (!tmp55_cast_fu_898_p1.read().is_01() || !tmp57_cast_fu_914_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp55_cast_fu_898_p1.read()) + sc_biguint<3>(tmp57_cast_fu_914_p1.read()));
}

void update_knn::thread_tmp_10_cast_fu_384_p1() {
    tmp_10_cast_fu_384_p1 = esl_zext<2,1>(tmp_13_fu_376_p3.read());
}

void update_knn::thread_tmp_10_fu_340_p3() {
    tmp_10_fu_340_p3 = r_V_fu_254_p2.read().range(7, 7);
}

void update_knn::thread_tmp_11_cast_fu_396_p1() {
    tmp_11_cast_fu_396_p1 = esl_zext<2,1>(tmp_14_fu_388_p3.read());
}

void update_knn::thread_tmp_11_fu_352_p3() {
    tmp_11_fu_352_p3 = r_V_fu_254_p2.read().range(8, 8);
}

void update_knn::thread_tmp_12_cast_fu_408_p1() {
    tmp_12_cast_fu_408_p1 = esl_zext<2,1>(tmp_15_fu_400_p3.read());
}

void update_knn::thread_tmp_12_fu_364_p3() {
    tmp_12_fu_364_p3 = r_V_fu_254_p2.read().range(9, 9);
}

void update_knn::thread_tmp_13_cast_fu_420_p1() {
    tmp_13_cast_fu_420_p1 = esl_zext<2,1>(tmp_16_fu_412_p3.read());
}

void update_knn::thread_tmp_13_fu_376_p3() {
    tmp_13_fu_376_p3 = r_V_fu_254_p2.read().range(10, 10);
}

void update_knn::thread_tmp_14_cast_fu_348_p1() {
    tmp_14_cast_fu_348_p1 = esl_zext<2,1>(tmp_10_fu_340_p3.read());
}

void update_knn::thread_tmp_14_fu_388_p3() {
    tmp_14_fu_388_p3 = r_V_fu_254_p2.read().range(11, 11);
}

void update_knn::thread_tmp_15_cast_fu_444_p1() {
    tmp_15_cast_fu_444_p1 = esl_zext<2,1>(tmp_18_fu_436_p3.read());
}

void update_knn::thread_tmp_15_fu_400_p3() {
    tmp_15_fu_400_p3 = r_V_fu_254_p2.read().range(12, 12);
}

void update_knn::thread_tmp_16_cast_fu_456_p1() {
    tmp_16_cast_fu_456_p1 = esl_zext<2,1>(tmp_19_fu_448_p3.read());
}

void update_knn::thread_tmp_16_fu_412_p3() {
    tmp_16_fu_412_p3 = r_V_fu_254_p2.read().range(13, 13);
}

void update_knn::thread_tmp_17_cast_fu_468_p1() {
    tmp_17_cast_fu_468_p1 = esl_zext<2,1>(tmp_20_fu_460_p3.read());
}

void update_knn::thread_tmp_17_fu_424_p3() {
    tmp_17_fu_424_p3 = r_V_fu_254_p2.read().range(14, 14);
}

void update_knn::thread_tmp_18_cast_fu_480_p1() {
    tmp_18_cast_fu_480_p1 = esl_zext<2,1>(tmp_21_fu_472_p3.read());
}

void update_knn::thread_tmp_18_fu_436_p3() {
    tmp_18_fu_436_p3 = r_V_fu_254_p2.read().range(15, 15);
}

void update_knn::thread_tmp_19_cast_fu_492_p1() {
    tmp_19_cast_fu_492_p1 = esl_zext<2,1>(tmp_22_fu_484_p3.read());
}

void update_knn::thread_tmp_19_fu_448_p3() {
    tmp_19_fu_448_p3 = r_V_fu_254_p2.read().range(16, 16);
}

void update_knn::thread_tmp_1_cast_fu_312_p1() {
    tmp_1_cast_fu_312_p1 = esl_zext<2,1>(tmp_7_fu_304_p3.read());
}

void update_knn::thread_tmp_1_fu_1284_p2() {
    tmp_1_fu_1284_p2 = (tmp_6_2_reg_1382.read() | tmp_6_1_reg_1347.read());
}

void update_knn::thread_tmp_20_cast_fu_504_p1() {
    tmp_20_cast_fu_504_p1 = esl_zext<2,1>(tmp_23_fu_496_p3.read());
}

void update_knn::thread_tmp_20_fu_460_p3() {
    tmp_20_fu_460_p3 = r_V_fu_254_p2.read().range(17, 17);
}

void update_knn::thread_tmp_21_cast_fu_516_p1() {
    tmp_21_cast_fu_516_p1 = esl_zext<2,1>(tmp_24_fu_508_p3.read());
}

void update_knn::thread_tmp_21_fu_472_p3() {
    tmp_21_fu_472_p3 = r_V_fu_254_p2.read().range(18, 18);
}

void update_knn::thread_tmp_22_cast_fu_528_p1() {
    tmp_22_cast_fu_528_p1 = esl_zext<2,1>(tmp_25_fu_520_p3.read());
}

void update_knn::thread_tmp_22_fu_484_p3() {
    tmp_22_fu_484_p3 = r_V_fu_254_p2.read().range(19, 19);
}

void update_knn::thread_tmp_23_cast_fu_540_p1() {
    tmp_23_cast_fu_540_p1 = esl_zext<2,1>(tmp_26_fu_532_p3.read());
}

void update_knn::thread_tmp_23_fu_496_p3() {
    tmp_23_fu_496_p3 = r_V_fu_254_p2.read().range(20, 20);
}

void update_knn::thread_tmp_24_cast_fu_552_p1() {
    tmp_24_cast_fu_552_p1 = esl_zext<2,1>(tmp_27_fu_544_p3.read());
}

void update_knn::thread_tmp_24_fu_508_p3() {
    tmp_24_fu_508_p3 = r_V_fu_254_p2.read().range(21, 21);
}

void update_knn::thread_tmp_25_cast_fu_564_p1() {
    tmp_25_cast_fu_564_p1 = esl_zext<2,1>(tmp_28_fu_556_p3.read());
}

void update_knn::thread_tmp_25_fu_520_p3() {
    tmp_25_fu_520_p3 = r_V_fu_254_p2.read().range(22, 22);
}

void update_knn::thread_tmp_26_cast_fu_576_p1() {
    tmp_26_cast_fu_576_p1 = esl_zext<2,1>(tmp_29_fu_568_p3.read());
}

void update_knn::thread_tmp_26_fu_532_p3() {
    tmp_26_fu_532_p3 = r_V_fu_254_p2.read().range(23, 23);
}

void update_knn::thread_tmp_27_cast_fu_588_p1() {
    tmp_27_cast_fu_588_p1 = esl_zext<2,1>(tmp_30_fu_580_p3.read());
}

void update_knn::thread_tmp_27_fu_544_p3() {
    tmp_27_fu_544_p3 = r_V_fu_254_p2.read().range(24, 24);
}

void update_knn::thread_tmp_28_cast_fu_600_p1() {
    tmp_28_cast_fu_600_p1 = esl_zext<2,1>(tmp_31_fu_592_p3.read());
}

void update_knn::thread_tmp_28_fu_556_p3() {
    tmp_28_fu_556_p3 = r_V_fu_254_p2.read().range(25, 25);
}

void update_knn::thread_tmp_29_cast_fu_612_p1() {
    tmp_29_cast_fu_612_p1 = esl_zext<2,1>(tmp_32_fu_604_p3.read());
}

void update_knn::thread_tmp_29_fu_568_p3() {
    tmp_29_fu_568_p3 = r_V_fu_254_p2.read().range(26, 26);
}

void update_knn::thread_tmp_2_cast_fu_288_p1() {
    tmp_2_cast_fu_288_p1 = esl_zext<2,1>(tmp_5_fu_280_p3.read());
}

void update_knn::thread_tmp_2_fu_260_p1() {
    tmp_2_fu_260_p1 = r_V_fu_254_p2.read().range(1-1, 0);
}

void update_knn::thread_tmp_30_cast_fu_624_p1() {
    tmp_30_cast_fu_624_p1 = esl_zext<2,1>(tmp_33_fu_616_p3.read());
}

void update_knn::thread_tmp_30_fu_580_p3() {
    tmp_30_fu_580_p3 = r_V_fu_254_p2.read().range(27, 27);
}

void update_knn::thread_tmp_31_cast_fu_636_p1() {
    tmp_31_cast_fu_636_p1 = esl_zext<2,1>(tmp_34_fu_628_p3.read());
}

void update_knn::thread_tmp_31_fu_592_p3() {
    tmp_31_fu_592_p3 = r_V_fu_254_p2.read().range(28, 28);
}

void update_knn::thread_tmp_32_cast_fu_648_p1() {
    tmp_32_cast_fu_648_p1 = esl_zext<2,1>(tmp_35_fu_640_p3.read());
}

void update_knn::thread_tmp_32_fu_604_p3() {
    tmp_32_fu_604_p3 = r_V_fu_254_p2.read().range(29, 29);
}

void update_knn::thread_tmp_33_cast_fu_660_p1() {
    tmp_33_cast_fu_660_p1 = esl_zext<2,1>(tmp_36_fu_652_p3.read());
}

void update_knn::thread_tmp_33_fu_616_p3() {
    tmp_33_fu_616_p3 = r_V_fu_254_p2.read().range(30, 30);
}

void update_knn::thread_tmp_34_cast_fu_672_p1() {
    tmp_34_cast_fu_672_p1 = esl_zext<2,1>(tmp_37_fu_664_p3.read());
}

void update_knn::thread_tmp_34_fu_628_p3() {
    tmp_34_fu_628_p3 = r_V_fu_254_p2.read().range(31, 31);
}

void update_knn::thread_tmp_35_cast_fu_684_p1() {
    tmp_35_cast_fu_684_p1 = esl_zext<2,1>(tmp_38_fu_676_p3.read());
}

void update_knn::thread_tmp_35_fu_640_p3() {
    tmp_35_fu_640_p3 = r_V_fu_254_p2.read().range(32, 32);
}

void update_knn::thread_tmp_36_cast_fu_696_p1() {
    tmp_36_cast_fu_696_p1 = esl_zext<2,1>(tmp_39_fu_688_p3.read());
}

void update_knn::thread_tmp_36_fu_652_p3() {
    tmp_36_fu_652_p3 = r_V_fu_254_p2.read().range(33, 33);
}

void update_knn::thread_tmp_37_cast_fu_708_p1() {
    tmp_37_cast_fu_708_p1 = esl_zext<2,1>(tmp_40_fu_700_p3.read());
}

void update_knn::thread_tmp_37_fu_664_p3() {
    tmp_37_fu_664_p3 = r_V_fu_254_p2.read().range(34, 34);
}

void update_knn::thread_tmp_38_cast_fu_720_p1() {
    tmp_38_cast_fu_720_p1 = esl_zext<2,1>(tmp_41_fu_712_p3.read());
}

void update_knn::thread_tmp_38_fu_676_p3() {
    tmp_38_fu_676_p3 = r_V_fu_254_p2.read().range(35, 35);
}

void update_knn::thread_tmp_39_cast_fu_732_p1() {
    tmp_39_cast_fu_732_p1 = esl_zext<2,1>(tmp_42_fu_724_p3.read());
}

void update_knn::thread_tmp_39_fu_688_p3() {
    tmp_39_fu_688_p3 = r_V_fu_254_p2.read().range(36, 36);
}

void update_knn::thread_tmp_3_cast_fu_300_p1() {
    tmp_3_cast_fu_300_p1 = esl_zext<2,1>(tmp_6_fu_292_p3.read());
}

void update_knn::thread_tmp_3_fu_268_p3() {
    tmp_3_fu_268_p3 = r_V_fu_254_p2.read().range(1, 1);
}

void update_knn::thread_tmp_40_cast_fu_744_p1() {
    tmp_40_cast_fu_744_p1 = esl_zext<2,1>(tmp_43_fu_736_p3.read());
}

void update_knn::thread_tmp_40_fu_700_p3() {
    tmp_40_fu_700_p3 = r_V_fu_254_p2.read().range(37, 37);
}

void update_knn::thread_tmp_41_cast_fu_756_p1() {
    tmp_41_cast_fu_756_p1 = esl_zext<2,1>(tmp_44_fu_748_p3.read());
}

void update_knn::thread_tmp_41_fu_712_p3() {
    tmp_41_fu_712_p3 = r_V_fu_254_p2.read().range(38, 38);
}

void update_knn::thread_tmp_42_cast_fu_768_p1() {
    tmp_42_cast_fu_768_p1 = esl_zext<2,1>(tmp_45_fu_760_p3.read());
}

void update_knn::thread_tmp_42_fu_724_p3() {
    tmp_42_fu_724_p3 = r_V_fu_254_p2.read().range(39, 39);
}

void update_knn::thread_tmp_43_cast_fu_780_p1() {
    tmp_43_cast_fu_780_p1 = esl_zext<2,1>(tmp_46_fu_772_p3.read());
}

void update_knn::thread_tmp_43_fu_736_p3() {
    tmp_43_fu_736_p3 = r_V_fu_254_p2.read().range(40, 40);
}

void update_knn::thread_tmp_44_cast_fu_792_p1() {
    tmp_44_cast_fu_792_p1 = esl_zext<2,1>(tmp_47_fu_784_p3.read());
}

void update_knn::thread_tmp_44_fu_748_p3() {
    tmp_44_fu_748_p3 = r_V_fu_254_p2.read().range(41, 41);
}

void update_knn::thread_tmp_45_cast_fu_432_p1() {
    tmp_45_cast_fu_432_p1 = esl_zext<2,1>(tmp_17_fu_424_p3.read());
}

void update_knn::thread_tmp_45_fu_760_p3() {
    tmp_45_fu_760_p3 = r_V_fu_254_p2.read().range(42, 42);
}

void update_knn::thread_tmp_46_cast_fu_816_p1() {
    tmp_46_cast_fu_816_p1 = esl_zext<2,1>(tmp_49_fu_808_p3.read());
}

void update_knn::thread_tmp_46_fu_772_p3() {
    tmp_46_fu_772_p3 = r_V_fu_254_p2.read().range(43, 43);
}

void update_knn::thread_tmp_47_cast_fu_828_p1() {
    tmp_47_cast_fu_828_p1 = esl_zext<2,1>(tmp_50_fu_820_p3.read());
}

void update_knn::thread_tmp_47_fu_784_p3() {
    tmp_47_fu_784_p3 = r_V_fu_254_p2.read().range(44, 44);
}

void update_knn::thread_tmp_48_cast_fu_840_p1() {
    tmp_48_cast_fu_840_p1 = esl_zext<2,1>(tmp_51_fu_832_p3.read());
}

void update_knn::thread_tmp_48_fu_796_p3() {
    tmp_48_fu_796_p3 = r_V_fu_254_p2.read().range(45, 45);
}

void update_knn::thread_tmp_49_cast_fu_804_p1() {
    tmp_49_cast_fu_804_p1 = esl_zext<2,1>(tmp_48_fu_796_p3.read());
}

void update_knn::thread_tmp_49_fu_808_p3() {
    tmp_49_fu_808_p3 = r_V_fu_254_p2.read().range(46, 46);
}

void update_knn::thread_tmp_4_fu_1296_p2() {
    tmp_4_fu_1296_p2 = (!dist_V_s_fu_1263_p2.read().is_01() || !min_distances_V_q0.read().is_01())? sc_lv<1>(): (sc_biguint<6>(dist_V_s_fu_1263_p2.read()) < sc_biguint<6>(min_distances_V_q0.read()));
}

void update_knn::thread_tmp_50_fu_820_p3() {
    tmp_50_fu_820_p3 = r_V_fu_254_p2.read().range(47, 47);
}

void update_knn::thread_tmp_51_fu_832_p3() {
    tmp_51_fu_832_p3 = r_V_fu_254_p2.read().range(48, 48);
}

void update_knn::thread_tmp_52_fu_204_p1() {
    tmp_52_fu_204_p1 = min_distances_V_offset.read().range(6-1, 0);
}

void update_knn::thread_tmp_53_fu_219_p1() {
    tmp_53_fu_219_p1 = min_distances_V_offset.read().range(32-1, 0);
}

void update_knn::thread_tmp_5_cast_fu_324_p1() {
    tmp_5_cast_fu_324_p1 = esl_zext<2,1>(tmp_8_fu_316_p3.read());
}

void update_knn::thread_tmp_5_fu_280_p3() {
    tmp_5_fu_280_p3 = r_V_fu_254_p2.read().range(2, 2);
}

void update_knn::thread_tmp_6_cast_fu_336_p1() {
    tmp_6_cast_fu_336_p1 = esl_zext<2,1>(tmp_9_fu_328_p3.read());
}

void update_knn::thread_tmp_6_fu_292_p3() {
    tmp_6_fu_292_p3 = r_V_fu_254_p2.read().range(3, 3);
}

void update_knn::thread_tmp_7_cast_fu_1302_p1() {
    tmp_7_cast_fu_1302_p1 = esl_zext<6,3>(p_max_dist_id_1_1_fu_1288_p3.read());
}

void update_knn::thread_tmp_7_fu_304_p3() {
    tmp_7_fu_304_p3 = r_V_fu_254_p2.read().range(4, 4);
}

void update_knn::thread_tmp_8_cast_fu_360_p1() {
    tmp_8_cast_fu_360_p1 = esl_zext<2,1>(tmp_11_fu_352_p3.read());
}

void update_knn::thread_tmp_8_fu_316_p3() {
    tmp_8_fu_316_p3 = r_V_fu_254_p2.read().range(5, 5);
}

void update_knn::thread_tmp_9_cast_fu_372_p1() {
    tmp_9_cast_fu_372_p1 = esl_zext<2,1>(tmp_12_fu_364_p3.read());
}

void update_knn::thread_tmp_9_fu_328_p3() {
    tmp_9_fu_328_p3 = r_V_fu_254_p2.read().range(6, 6);
}

void update_knn::thread_tmp_cast_7_fu_276_p1() {
    tmp_cast_7_fu_276_p1 = esl_zext<2,1>(tmp_3_fu_268_p3.read());
}

void update_knn::thread_tmp_cast_fu_264_p1() {
    tmp_cast_fu_264_p1 = esl_zext<2,1>(tmp_2_fu_260_p1.read());
}

void update_knn::thread_tmp_fu_844_p2() {
    tmp_fu_844_p2 = (!tmp_49_cast_fu_804_p1.read().is_01() || !tmp_47_cast_fu_828_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_49_cast_fu_804_p1.read()) + sc_biguint<2>(tmp_47_cast_fu_828_p1.read()));
}

void update_knn::thread_tmp_s_fu_223_p2() {
    tmp_s_fu_223_p2 = (!min_distances_V_q0.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(min_distances_V_q0.read() == ap_const_lv6_0);
}

void update_knn::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

